/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables;


import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tito.jooq.Greygold;
import ru.tito.jooq.Keys;
import ru.tito.jooq.tables.records.ActGePropertyRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActGeProperty extends TableImpl<ActGePropertyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>greygold.act_ge_property</code>
     */
    public static final ActGeProperty ACT_GE_PROPERTY = new ActGeProperty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActGePropertyRecord> getRecordType() {
        return ActGePropertyRecord.class;
    }

    /**
     * The column <code>greygold.act_ge_property.name_</code>.
     */
    public final TableField<ActGePropertyRecord, String> NAME_ = createField(DSL.name("name_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_ge_property.value_</code>.
     */
    public final TableField<ActGePropertyRecord, String> VALUE_ = createField(DSL.name("value_"), SQLDataType.VARCHAR(300), this, "");

    /**
     * The column <code>greygold.act_ge_property.rev_</code>.
     */
    public final TableField<ActGePropertyRecord, Integer> REV_ = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "");

    private ActGeProperty(Name alias, Table<ActGePropertyRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActGeProperty(Name alias, Table<ActGePropertyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>greygold.act_ge_property</code> table reference
     */
    public ActGeProperty(String alias) {
        this(DSL.name(alias), ACT_GE_PROPERTY);
    }

    /**
     * Create an aliased <code>greygold.act_ge_property</code> table reference
     */
    public ActGeProperty(Name alias) {
        this(alias, ACT_GE_PROPERTY);
    }

    /**
     * Create a <code>greygold.act_ge_property</code> table reference
     */
    public ActGeProperty() {
        this(DSL.name("act_ge_property"), null);
    }

    public <O extends Record> ActGeProperty(Table<O> child, ForeignKey<O, ActGePropertyRecord> key) {
        super(child, key, ACT_GE_PROPERTY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Greygold.GREYGOLD;
    }

    @Override
    public UniqueKey<ActGePropertyRecord> getPrimaryKey() {
        return Keys.ACT_GE_PROPERTY_PKEY;
    }

    @Override
    public ActGeProperty as(String alias) {
        return new ActGeProperty(DSL.name(alias), this);
    }

    @Override
    public ActGeProperty as(Name alias) {
        return new ActGeProperty(alias, this);
    }

    @Override
    public ActGeProperty as(Table<?> alias) {
        return new ActGeProperty(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActGeProperty rename(String name) {
        return new ActGeProperty(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActGeProperty rename(Name name) {
        return new ActGeProperty(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActGeProperty rename(Table<?> name) {
        return new ActGeProperty(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
