/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function14;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tito.jooq.Greygold;
import ru.tito.jooq.Indexes;
import ru.tito.jooq.Keys;
import ru.tito.jooq.tables.records.ActHiDecInRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiDecIn extends TableImpl<ActHiDecInRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>greygold.act_hi_dec_in</code>
     */
    public static final ActHiDecIn ACT_HI_DEC_IN = new ActHiDecIn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActHiDecInRecord> getRecordType() {
        return ActHiDecInRecord.class;
    }

    /**
     * The column <code>greygold.act_hi_dec_in.id_</code>.
     */
    public final TableField<ActHiDecInRecord, String> ID_ = createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.dec_inst_id_</code>.
     */
    public final TableField<ActHiDecInRecord, String> DEC_INST_ID_ = createField(DSL.name("dec_inst_id_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.clause_id_</code>.
     */
    public final TableField<ActHiDecInRecord, String> CLAUSE_ID_ = createField(DSL.name("clause_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.clause_name_</code>.
     */
    public final TableField<ActHiDecInRecord, String> CLAUSE_NAME_ = createField(DSL.name("clause_name_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.var_type_</code>.
     */
    public final TableField<ActHiDecInRecord, String> VAR_TYPE_ = createField(DSL.name("var_type_"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.bytearray_id_</code>.
     */
    public final TableField<ActHiDecInRecord, String> BYTEARRAY_ID_ = createField(DSL.name("bytearray_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.double_</code>.
     */
    public final TableField<ActHiDecInRecord, Double> DOUBLE_ = createField(DSL.name("double_"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.long_</code>.
     */
    public final TableField<ActHiDecInRecord, Long> LONG_ = createField(DSL.name("long_"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.text_</code>.
     */
    public final TableField<ActHiDecInRecord, String> TEXT_ = createField(DSL.name("text_"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.text2_</code>.
     */
    public final TableField<ActHiDecInRecord, String> TEXT2_ = createField(DSL.name("text2_"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.tenant_id_</code>.
     */
    public final TableField<ActHiDecInRecord, String> TENANT_ID_ = createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.create_time_</code>.
     */
    public final TableField<ActHiDecInRecord, LocalDateTime> CREATE_TIME_ = createField(DSL.name("create_time_"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.root_proc_inst_id_</code>.
     */
    public final TableField<ActHiDecInRecord, String> ROOT_PROC_INST_ID_ = createField(DSL.name("root_proc_inst_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_dec_in.removal_time_</code>.
     */
    public final TableField<ActHiDecInRecord, LocalDateTime> REMOVAL_TIME_ = createField(DSL.name("removal_time_"), SQLDataType.LOCALDATETIME(6), this, "");

    private ActHiDecIn(Name alias, Table<ActHiDecInRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActHiDecIn(Name alias, Table<ActHiDecInRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>greygold.act_hi_dec_in</code> table reference
     */
    public ActHiDecIn(String alias) {
        this(DSL.name(alias), ACT_HI_DEC_IN);
    }

    /**
     * Create an aliased <code>greygold.act_hi_dec_in</code> table reference
     */
    public ActHiDecIn(Name alias) {
        this(alias, ACT_HI_DEC_IN);
    }

    /**
     * Create a <code>greygold.act_hi_dec_in</code> table reference
     */
    public ActHiDecIn() {
        this(DSL.name("act_hi_dec_in"), null);
    }

    public <O extends Record> ActHiDecIn(Table<O> child, ForeignKey<O, ActHiDecInRecord> key) {
        super(child, key, ACT_HI_DEC_IN);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Greygold.GREYGOLD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACT_IDX_HI_DEC_IN_CLAUSE, Indexes.ACT_IDX_HI_DEC_IN_INST, Indexes.ACT_IDX_HI_DEC_IN_RM_TIME, Indexes.ACT_IDX_HI_DEC_IN_ROOT_PI);
    }

    @Override
    public UniqueKey<ActHiDecInRecord> getPrimaryKey() {
        return Keys.ACT_HI_DEC_IN_PKEY;
    }

    @Override
    public ActHiDecIn as(String alias) {
        return new ActHiDecIn(DSL.name(alias), this);
    }

    @Override
    public ActHiDecIn as(Name alias) {
        return new ActHiDecIn(alias, this);
    }

    @Override
    public ActHiDecIn as(Table<?> alias) {
        return new ActHiDecIn(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiDecIn rename(String name) {
        return new ActHiDecIn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiDecIn rename(Name name) {
        return new ActHiDecIn(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiDecIn rename(Table<?> name) {
        return new ActHiDecIn(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, String, String, String, String, String, Double, Long, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function14<? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Double, ? super Long, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function14<? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Double, ? super Long, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
