/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tito.jooq.Greygold;
import ru.tito.jooq.Indexes;
import ru.tito.jooq.Keys;
import ru.tito.jooq.tables.records.ActHiJobLogRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiJobLog extends TableImpl<ActHiJobLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>greygold.act_hi_job_log</code>
     */
    public static final ActHiJobLog ACT_HI_JOB_LOG = new ActHiJobLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActHiJobLogRecord> getRecordType() {
        return ActHiJobLogRecord.class;
    }

    /**
     * The column <code>greygold.act_hi_job_log.id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> ID_ = createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.timestamp_</code>.
     */
    public final TableField<ActHiJobLogRecord, LocalDateTime> TIMESTAMP_ = createField(DSL.name("timestamp_"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> JOB_ID_ = createField(DSL.name("job_id_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_duedate_</code>.
     */
    public final TableField<ActHiJobLogRecord, LocalDateTime> JOB_DUEDATE_ = createField(DSL.name("job_duedate_"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_retries_</code>.
     */
    public final TableField<ActHiJobLogRecord, Integer> JOB_RETRIES_ = createField(DSL.name("job_retries_"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_priority_</code>.
     */
    public final TableField<ActHiJobLogRecord, Long> JOB_PRIORITY_ = createField(DSL.name("job_priority_"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_exception_msg_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> JOB_EXCEPTION_MSG_ = createField(DSL.name("job_exception_msg_"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_exception_stack_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> JOB_EXCEPTION_STACK_ID_ = createField(DSL.name("job_exception_stack_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_state_</code>.
     */
    public final TableField<ActHiJobLogRecord, Integer> JOB_STATE_ = createField(DSL.name("job_state_"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_def_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> JOB_DEF_ID_ = createField(DSL.name("job_def_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_def_type_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> JOB_DEF_TYPE_ = createField(DSL.name("job_def_type_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.job_def_configuration_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> JOB_DEF_CONFIGURATION_ = createField(DSL.name("job_def_configuration_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.act_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> ACT_ID_ = createField(DSL.name("act_id_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.failed_act_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> FAILED_ACT_ID_ = createField(DSL.name("failed_act_id_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.execution_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> EXECUTION_ID_ = createField(DSL.name("execution_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.root_proc_inst_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> ROOT_PROC_INST_ID_ = createField(DSL.name("root_proc_inst_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.process_instance_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> PROCESS_INSTANCE_ID_ = createField(DSL.name("process_instance_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.process_def_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> PROCESS_DEF_ID_ = createField(DSL.name("process_def_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.process_def_key_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> PROCESS_DEF_KEY_ = createField(DSL.name("process_def_key_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.deployment_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> DEPLOYMENT_ID_ = createField(DSL.name("deployment_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.sequence_counter_</code>.
     */
    public final TableField<ActHiJobLogRecord, Long> SEQUENCE_COUNTER_ = createField(DSL.name("sequence_counter_"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>greygold.act_hi_job_log.tenant_id_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> TENANT_ID_ = createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.hostname_</code>.
     */
    public final TableField<ActHiJobLogRecord, String> HOSTNAME_ = createField(DSL.name("hostname_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_job_log.removal_time_</code>.
     */
    public final TableField<ActHiJobLogRecord, LocalDateTime> REMOVAL_TIME_ = createField(DSL.name("removal_time_"), SQLDataType.LOCALDATETIME(6), this, "");

    private ActHiJobLog(Name alias, Table<ActHiJobLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActHiJobLog(Name alias, Table<ActHiJobLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>greygold.act_hi_job_log</code> table reference
     */
    public ActHiJobLog(String alias) {
        this(DSL.name(alias), ACT_HI_JOB_LOG);
    }

    /**
     * Create an aliased <code>greygold.act_hi_job_log</code> table reference
     */
    public ActHiJobLog(Name alias) {
        this(alias, ACT_HI_JOB_LOG);
    }

    /**
     * Create a <code>greygold.act_hi_job_log</code> table reference
     */
    public ActHiJobLog() {
        this(DSL.name("act_hi_job_log"), null);
    }

    public <O extends Record> ActHiJobLog(Table<O> child, ForeignKey<O, ActHiJobLogRecord> key) {
        super(child, key, ACT_HI_JOB_LOG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Greygold.GREYGOLD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACT_IDX_HI_JOB_LOG_EX_STACK, Indexes.ACT_IDX_HI_JOB_LOG_JOB_CONF, Indexes.ACT_IDX_HI_JOB_LOG_JOB_DEF_ID, Indexes.ACT_IDX_HI_JOB_LOG_PROC_DEF_KEY, Indexes.ACT_IDX_HI_JOB_LOG_PROCDEF, Indexes.ACT_IDX_HI_JOB_LOG_PROCINST, Indexes.ACT_IDX_HI_JOB_LOG_RM_TIME, Indexes.ACT_IDX_HI_JOB_LOG_ROOT_PI, Indexes.ACT_IDX_HI_JOB_LOG_TENANT_ID);
    }

    @Override
    public UniqueKey<ActHiJobLogRecord> getPrimaryKey() {
        return Keys.ACT_HI_JOB_LOG_PKEY;
    }

    @Override
    public ActHiJobLog as(String alias) {
        return new ActHiJobLog(DSL.name(alias), this);
    }

    @Override
    public ActHiJobLog as(Name alias) {
        return new ActHiJobLog(alias, this);
    }

    @Override
    public ActHiJobLog as(Table<?> alias) {
        return new ActHiJobLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiJobLog rename(String name) {
        return new ActHiJobLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiJobLog rename(Name name) {
        return new ActHiJobLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiJobLog rename(Table<?> name) {
        return new ActHiJobLog(name.getQualifiedName(), null);
    }
}
