/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tito.jooq.Greygold;
import ru.tito.jooq.Indexes;
import ru.tito.jooq.Keys;
import ru.tito.jooq.tables.records.ActHiTaskinstRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiTaskinst extends TableImpl<ActHiTaskinstRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>greygold.act_hi_taskinst</code>
     */
    public static final ActHiTaskinst ACT_HI_TASKINST = new ActHiTaskinst();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActHiTaskinstRecord> getRecordType() {
        return ActHiTaskinstRecord.class;
    }

    /**
     * The column <code>greygold.act_hi_taskinst.id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> ID_ = createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.task_def_key_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> TASK_DEF_KEY_ = createField(DSL.name("task_def_key_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.proc_def_key_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> PROC_DEF_KEY_ = createField(DSL.name("proc_def_key_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.proc_def_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> PROC_DEF_ID_ = createField(DSL.name("proc_def_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.root_proc_inst_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> ROOT_PROC_INST_ID_ = createField(DSL.name("root_proc_inst_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.proc_inst_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> PROC_INST_ID_ = createField(DSL.name("proc_inst_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.execution_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> EXECUTION_ID_ = createField(DSL.name("execution_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.case_def_key_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> CASE_DEF_KEY_ = createField(DSL.name("case_def_key_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.case_def_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> CASE_DEF_ID_ = createField(DSL.name("case_def_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.case_inst_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> CASE_INST_ID_ = createField(DSL.name("case_inst_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.case_execution_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> CASE_EXECUTION_ID_ = createField(DSL.name("case_execution_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.act_inst_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> ACT_INST_ID_ = createField(DSL.name("act_inst_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.name_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> NAME_ = createField(DSL.name("name_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.parent_task_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> PARENT_TASK_ID_ = createField(DSL.name("parent_task_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.description_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> DESCRIPTION_ = createField(DSL.name("description_"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.owner_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> OWNER_ = createField(DSL.name("owner_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.assignee_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> ASSIGNEE_ = createField(DSL.name("assignee_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.start_time_</code>.
     */
    public final TableField<ActHiTaskinstRecord, LocalDateTime> START_TIME_ = createField(DSL.name("start_time_"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.end_time_</code>.
     */
    public final TableField<ActHiTaskinstRecord, LocalDateTime> END_TIME_ = createField(DSL.name("end_time_"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.duration_</code>.
     */
    public final TableField<ActHiTaskinstRecord, Long> DURATION_ = createField(DSL.name("duration_"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.delete_reason_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> DELETE_REASON_ = createField(DSL.name("delete_reason_"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.priority_</code>.
     */
    public final TableField<ActHiTaskinstRecord, Integer> PRIORITY_ = createField(DSL.name("priority_"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.due_date_</code>.
     */
    public final TableField<ActHiTaskinstRecord, LocalDateTime> DUE_DATE_ = createField(DSL.name("due_date_"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.follow_up_date_</code>.
     */
    public final TableField<ActHiTaskinstRecord, LocalDateTime> FOLLOW_UP_DATE_ = createField(DSL.name("follow_up_date_"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.tenant_id_</code>.
     */
    public final TableField<ActHiTaskinstRecord, String> TENANT_ID_ = createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_hi_taskinst.removal_time_</code>.
     */
    public final TableField<ActHiTaskinstRecord, LocalDateTime> REMOVAL_TIME_ = createField(DSL.name("removal_time_"), SQLDataType.LOCALDATETIME(6), this, "");

    private ActHiTaskinst(Name alias, Table<ActHiTaskinstRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActHiTaskinst(Name alias, Table<ActHiTaskinstRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>greygold.act_hi_taskinst</code> table reference
     */
    public ActHiTaskinst(String alias) {
        this(DSL.name(alias), ACT_HI_TASKINST);
    }

    /**
     * Create an aliased <code>greygold.act_hi_taskinst</code> table reference
     */
    public ActHiTaskinst(Name alias) {
        this(alias, ACT_HI_TASKINST);
    }

    /**
     * Create a <code>greygold.act_hi_taskinst</code> table reference
     */
    public ActHiTaskinst() {
        this(DSL.name("act_hi_taskinst"), null);
    }

    public <O extends Record> ActHiTaskinst(Table<O> child, ForeignKey<O, ActHiTaskinstRecord> key) {
        super(child, key, ACT_HI_TASKINST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Greygold.GREYGOLD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACT_IDX_HI_TASK_INST_END, Indexes.ACT_IDX_HI_TASK_INST_PROC_DEF_KEY, Indexes.ACT_IDX_HI_TASK_INST_RM_TIME, Indexes.ACT_IDX_HI_TASK_INST_START, Indexes.ACT_IDX_HI_TASK_INST_TENANT_ID, Indexes.ACT_IDX_HI_TASKINST_PROCINST, Indexes.ACT_IDX_HI_TASKINST_ROOT_PI, Indexes.ACT_IDX_HI_TASKINSTID_PROCINST);
    }

    @Override
    public UniqueKey<ActHiTaskinstRecord> getPrimaryKey() {
        return Keys.ACT_HI_TASKINST_PKEY;
    }

    @Override
    public ActHiTaskinst as(String alias) {
        return new ActHiTaskinst(DSL.name(alias), this);
    }

    @Override
    public ActHiTaskinst as(Name alias) {
        return new ActHiTaskinst(alias, this);
    }

    @Override
    public ActHiTaskinst as(Table<?> alias) {
        return new ActHiTaskinst(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiTaskinst rename(String name) {
        return new ActHiTaskinst(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiTaskinst rename(Name name) {
        return new ActHiTaskinst(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActHiTaskinst rename(Table<?> name) {
        return new ActHiTaskinst(name.getQualifiedName(), null);
    }
}
