/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function14;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tito.jooq.Greygold;
import ru.tito.jooq.Indexes;
import ru.tito.jooq.Keys;
import ru.tito.jooq.tables.records.ActReDecisionDefRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActReDecisionDef extends TableImpl<ActReDecisionDefRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>greygold.act_re_decision_def</code>
     */
    public static final ActReDecisionDef ACT_RE_DECISION_DEF = new ActReDecisionDef();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActReDecisionDefRecord> getRecordType() {
        return ActReDecisionDefRecord.class;
    }

    /**
     * The column <code>greygold.act_re_decision_def.id_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> ID_ = createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.rev_</code>.
     */
    public final TableField<ActReDecisionDefRecord, Integer> REV_ = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>greygold.act_re_decision_def.category_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> CATEGORY_ = createField(DSL.name("category_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.name_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> NAME_ = createField(DSL.name("name_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.key_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> KEY_ = createField(DSL.name("key_"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.version_</code>.
     */
    public final TableField<ActReDecisionDefRecord, Integer> VERSION_ = createField(DSL.name("version_"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.deployment_id_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> DEPLOYMENT_ID_ = createField(DSL.name("deployment_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.resource_name_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> RESOURCE_NAME_ = createField(DSL.name("resource_name_"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.dgrm_resource_name_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> DGRM_RESOURCE_NAME_ = createField(DSL.name("dgrm_resource_name_"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.dec_req_id_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> DEC_REQ_ID_ = createField(DSL.name("dec_req_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.dec_req_key_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> DEC_REQ_KEY_ = createField(DSL.name("dec_req_key_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.tenant_id_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> TENANT_ID_ = createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>greygold.act_re_decision_def.history_ttl_</code>.
     */
    public final TableField<ActReDecisionDefRecord, Integer> HISTORY_TTL_ = createField(DSL.name("history_ttl_"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>greygold.act_re_decision_def.version_tag_</code>.
     */
    public final TableField<ActReDecisionDefRecord, String> VERSION_TAG_ = createField(DSL.name("version_tag_"), SQLDataType.VARCHAR(64), this, "");

    private ActReDecisionDef(Name alias, Table<ActReDecisionDefRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActReDecisionDef(Name alias, Table<ActReDecisionDefRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>greygold.act_re_decision_def</code> table
     * reference
     */
    public ActReDecisionDef(String alias) {
        this(DSL.name(alias), ACT_RE_DECISION_DEF);
    }

    /**
     * Create an aliased <code>greygold.act_re_decision_def</code> table
     * reference
     */
    public ActReDecisionDef(Name alias) {
        this(alias, ACT_RE_DECISION_DEF);
    }

    /**
     * Create a <code>greygold.act_re_decision_def</code> table reference
     */
    public ActReDecisionDef() {
        this(DSL.name("act_re_decision_def"), null);
    }

    public <O extends Record> ActReDecisionDef(Table<O> child, ForeignKey<O, ActReDecisionDefRecord> key) {
        super(child, key, ACT_RE_DECISION_DEF);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Greygold.GREYGOLD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACT_IDX_DEC_DEF_REQ_ID, Indexes.ACT_IDX_DEC_DEF_TENANT_ID);
    }

    @Override
    public UniqueKey<ActReDecisionDefRecord> getPrimaryKey() {
        return Keys.ACT_RE_DECISION_DEF_PKEY;
    }

    @Override
    public List<ForeignKey<ActReDecisionDefRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACT_RE_DECISION_DEF__ACT_FK_DEC_REQ);
    }

    private transient ActReDecisionReqDef _actReDecisionReqDef;

    /**
     * Get the implicit join path to the
     * <code>greygold.act_re_decision_req_def</code> table.
     */
    public ActReDecisionReqDef actReDecisionReqDef() {
        if (_actReDecisionReqDef == null)
            _actReDecisionReqDef = new ActReDecisionReqDef(this, Keys.ACT_RE_DECISION_DEF__ACT_FK_DEC_REQ);

        return _actReDecisionReqDef;
    }

    @Override
    public ActReDecisionDef as(String alias) {
        return new ActReDecisionDef(DSL.name(alias), this);
    }

    @Override
    public ActReDecisionDef as(Name alias) {
        return new ActReDecisionDef(alias, this);
    }

    @Override
    public ActReDecisionDef as(Table<?> alias) {
        return new ActReDecisionDef(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActReDecisionDef rename(String name) {
        return new ActReDecisionDef(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActReDecisionDef rename(Name name) {
        return new ActReDecisionDef(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActReDecisionDef rename(Table<?> name) {
        return new ActReDecisionDef(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, Integer, String, String, String, Integer, String, String, String, String, String, String, Integer, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function14<? super String, ? super Integer, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function14<? super String, ? super Integer, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
