/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tito.jooq.Greygold;
import ru.tito.jooq.Indexes;
import ru.tito.jooq.Keys;
import ru.tito.jooq.tables.records.ActRuMeterLogRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuMeterLog extends TableImpl<ActRuMeterLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>greygold.act_ru_meter_log</code>
     */
    public static final ActRuMeterLog ACT_RU_METER_LOG = new ActRuMeterLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActRuMeterLogRecord> getRecordType() {
        return ActRuMeterLogRecord.class;
    }

    /**
     * The column <code>greygold.act_ru_meter_log.id_</code>.
     */
    public final TableField<ActRuMeterLogRecord, String> ID_ = createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_ru_meter_log.name_</code>.
     */
    public final TableField<ActRuMeterLogRecord, String> NAME_ = createField(DSL.name("name_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_ru_meter_log.reporter_</code>.
     */
    public final TableField<ActRuMeterLogRecord, String> REPORTER_ = createField(DSL.name("reporter_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_ru_meter_log.value_</code>.
     */
    public final TableField<ActRuMeterLogRecord, Long> VALUE_ = createField(DSL.name("value_"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>greygold.act_ru_meter_log.timestamp_</code>.
     */
    public final TableField<ActRuMeterLogRecord, LocalDateTime> TIMESTAMP_ = createField(DSL.name("timestamp_"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>greygold.act_ru_meter_log.milliseconds_</code>.
     */
    public final TableField<ActRuMeterLogRecord, Long> MILLISECONDS_ = createField(DSL.name("milliseconds_"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private ActRuMeterLog(Name alias, Table<ActRuMeterLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActRuMeterLog(Name alias, Table<ActRuMeterLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>greygold.act_ru_meter_log</code> table reference
     */
    public ActRuMeterLog(String alias) {
        this(DSL.name(alias), ACT_RU_METER_LOG);
    }

    /**
     * Create an aliased <code>greygold.act_ru_meter_log</code> table reference
     */
    public ActRuMeterLog(Name alias) {
        this(alias, ACT_RU_METER_LOG);
    }

    /**
     * Create a <code>greygold.act_ru_meter_log</code> table reference
     */
    public ActRuMeterLog() {
        this(DSL.name("act_ru_meter_log"), null);
    }

    public <O extends Record> ActRuMeterLog(Table<O> child, ForeignKey<O, ActRuMeterLogRecord> key) {
        super(child, key, ACT_RU_METER_LOG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Greygold.GREYGOLD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACT_IDX_METER_LOG, Indexes.ACT_IDX_METER_LOG_MS, Indexes.ACT_IDX_METER_LOG_NAME_MS, Indexes.ACT_IDX_METER_LOG_REPORT, Indexes.ACT_IDX_METER_LOG_TIME);
    }

    @Override
    public UniqueKey<ActRuMeterLogRecord> getPrimaryKey() {
        return Keys.ACT_RU_METER_LOG_PKEY;
    }

    @Override
    public ActRuMeterLog as(String alias) {
        return new ActRuMeterLog(DSL.name(alias), this);
    }

    @Override
    public ActRuMeterLog as(Name alias) {
        return new ActRuMeterLog(alias, this);
    }

    @Override
    public ActRuMeterLog as(Table<?> alias) {
        return new ActRuMeterLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuMeterLog rename(String name) {
        return new ActRuMeterLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuMeterLog rename(Name name) {
        return new ActRuMeterLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuMeterLog rename(Table<?> name) {
        return new ActRuMeterLog(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, Long, LocalDateTime, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super String, ? super String, ? super String, ? super Long, ? super LocalDateTime, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super String, ? super String, ? super String, ? super Long, ? super LocalDateTime, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
