/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tito.jooq.Greygold;
import ru.tito.jooq.Indexes;
import ru.tito.jooq.Keys;
import ru.tito.jooq.tables.records.ActRuAuthorizationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuAuthorization extends TableImpl<ActRuAuthorizationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>greygold.act_ru_authorization</code>
     */
    public static final ActRuAuthorization ACT_RU_AUTHORIZATION = new ActRuAuthorization();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActRuAuthorizationRecord> getRecordType() {
        return ActRuAuthorizationRecord.class;
    }

    /**
     * The column <code>greygold.act_ru_authorization.id_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, String> ID_ = createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>greygold.act_ru_authorization.rev_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, Integer> REV_ = createField(DSL.name("rev_"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>greygold.act_ru_authorization.type_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, Integer> TYPE_ = createField(DSL.name("type_"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>greygold.act_ru_authorization.group_id_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, String> GROUP_ID_ = createField(DSL.name("group_id_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_ru_authorization.user_id_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, String> USER_ID_ = createField(DSL.name("user_id_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_ru_authorization.resource_type_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, Integer> RESOURCE_TYPE_ = createField(DSL.name("resource_type_"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>greygold.act_ru_authorization.resource_id_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, String> RESOURCE_ID_ = createField(DSL.name("resource_id_"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>greygold.act_ru_authorization.perms_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, Integer> PERMS_ = createField(DSL.name("perms_"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>greygold.act_ru_authorization.removal_time_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, LocalDateTime> REMOVAL_TIME_ = createField(DSL.name("removal_time_"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>greygold.act_ru_authorization.root_proc_inst_id_</code>.
     */
    public final TableField<ActRuAuthorizationRecord, String> ROOT_PROC_INST_ID_ = createField(DSL.name("root_proc_inst_id_"), SQLDataType.VARCHAR(64), this, "");

    private ActRuAuthorization(Name alias, Table<ActRuAuthorizationRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActRuAuthorization(Name alias, Table<ActRuAuthorizationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>greygold.act_ru_authorization</code> table
     * reference
     */
    public ActRuAuthorization(String alias) {
        this(DSL.name(alias), ACT_RU_AUTHORIZATION);
    }

    /**
     * Create an aliased <code>greygold.act_ru_authorization</code> table
     * reference
     */
    public ActRuAuthorization(Name alias) {
        this(alias, ACT_RU_AUTHORIZATION);
    }

    /**
     * Create a <code>greygold.act_ru_authorization</code> table reference
     */
    public ActRuAuthorization() {
        this(DSL.name("act_ru_authorization"), null);
    }

    public <O extends Record> ActRuAuthorization(Table<O> child, ForeignKey<O, ActRuAuthorizationRecord> key) {
        super(child, key, ACT_RU_AUTHORIZATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Greygold.GREYGOLD;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACT_IDX_AUTH_GROUP_ID, Indexes.ACT_IDX_AUTH_RESOURCE_ID, Indexes.ACT_IDX_AUTH_RM_TIME, Indexes.ACT_IDX_AUTH_ROOT_PI);
    }

    @Override
    public UniqueKey<ActRuAuthorizationRecord> getPrimaryKey() {
        return Keys.ACT_RU_AUTHORIZATION_PKEY;
    }

    @Override
    public List<UniqueKey<ActRuAuthorizationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ACT_UNIQ_AUTH_GROUP, Keys.ACT_UNIQ_AUTH_USER);
    }

    @Override
    public ActRuAuthorization as(String alias) {
        return new ActRuAuthorization(DSL.name(alias), this);
    }

    @Override
    public ActRuAuthorization as(Name alias) {
        return new ActRuAuthorization(alias, this);
    }

    @Override
    public ActRuAuthorization as(Table<?> alias) {
        return new ActRuAuthorization(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuAuthorization rename(String name) {
        return new ActRuAuthorization(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuAuthorization rename(Name name) {
        return new ActRuAuthorization(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActRuAuthorization rename(Table<?> name) {
        return new ActRuAuthorization(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, Integer, Integer, String, String, Integer, String, Integer, LocalDateTime, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super String, ? super Integer, ? super Integer, ? super String, ? super String, ? super Integer, ? super String, ? super Integer, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super String, ? super Integer, ? super Integer, ? super String, ? super String, ? super Integer, ? super String, ? super Integer, ? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
