version: "2"
services:
  postgres:
    image: postgres:16.1-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: grey
      POSTGRES_PASSWORD: postgrey
      POSTGRES_DB: postgres
    profiles:
      - v1