/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActHiCaseinst;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiCaseinstRecord extends UpdatableRecordImpl<ActHiCaseinstRecord> implements Record12<String, String, String, String, LocalDateTime, LocalDateTime, Long, Integer, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_hi_caseinst.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.case_inst_id_</code>.
     */
    public void setCaseInstId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.case_inst_id_</code>.
     */
    public String getCaseInstId_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.business_key_</code>.
     */
    public void setBusinessKey_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.business_key_</code>.
     */
    public String getBusinessKey_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.case_def_id_</code>.
     */
    public void setCaseDefId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.case_def_id_</code>.
     */
    public String getCaseDefId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.create_time_</code>.
     */
    public void setCreateTime_(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.create_time_</code>.
     */
    public LocalDateTime getCreateTime_() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.close_time_</code>.
     */
    public void setCloseTime_(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.close_time_</code>.
     */
    public LocalDateTime getCloseTime_() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.duration_</code>.
     */
    public void setDuration_(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.duration_</code>.
     */
    public Long getDuration_() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.state_</code>.
     */
    public void setState_(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.state_</code>.
     */
    public Integer getState_() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.create_user_id_</code>.
     */
    public void setCreateUserId_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.create_user_id_</code>.
     */
    public String getCreateUserId_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.super_case_instance_id_</code>.
     */
    public void setSuperCaseInstanceId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.super_case_instance_id_</code>.
     */
    public String getSuperCaseInstanceId_() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>greygold.act_hi_caseinst.super_process_instance_id_</code>.
     */
    public void setSuperProcessInstanceId_(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>greygold.act_hi_caseinst.super_process_instance_id_</code>.
     */
    public String getSuperProcessInstanceId_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>greygold.act_hi_caseinst.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseinst.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, String, String, String, LocalDateTime, LocalDateTime, Long, Integer, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<String, String, String, String, LocalDateTime, LocalDateTime, Long, Integer, String, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiCaseinst.ACT_HI_CASEINST.ID_;
    }

    @Override
    public Field<String> field2() {
        return ActHiCaseinst.ACT_HI_CASEINST.CASE_INST_ID_;
    }

    @Override
    public Field<String> field3() {
        return ActHiCaseinst.ACT_HI_CASEINST.BUSINESS_KEY_;
    }

    @Override
    public Field<String> field4() {
        return ActHiCaseinst.ACT_HI_CASEINST.CASE_DEF_ID_;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ActHiCaseinst.ACT_HI_CASEINST.CREATE_TIME_;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ActHiCaseinst.ACT_HI_CASEINST.CLOSE_TIME_;
    }

    @Override
    public Field<Long> field7() {
        return ActHiCaseinst.ACT_HI_CASEINST.DURATION_;
    }

    @Override
    public Field<Integer> field8() {
        return ActHiCaseinst.ACT_HI_CASEINST.STATE_;
    }

    @Override
    public Field<String> field9() {
        return ActHiCaseinst.ACT_HI_CASEINST.CREATE_USER_ID_;
    }

    @Override
    public Field<String> field10() {
        return ActHiCaseinst.ACT_HI_CASEINST.SUPER_CASE_INSTANCE_ID_;
    }

    @Override
    public Field<String> field11() {
        return ActHiCaseinst.ACT_HI_CASEINST.SUPER_PROCESS_INSTANCE_ID_;
    }

    @Override
    public Field<String> field12() {
        return ActHiCaseinst.ACT_HI_CASEINST.TENANT_ID_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getCaseInstId_();
    }

    @Override
    public String component3() {
        return getBusinessKey_();
    }

    @Override
    public String component4() {
        return getCaseDefId_();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime_();
    }

    @Override
    public LocalDateTime component6() {
        return getCloseTime_();
    }

    @Override
    public Long component7() {
        return getDuration_();
    }

    @Override
    public Integer component8() {
        return getState_();
    }

    @Override
    public String component9() {
        return getCreateUserId_();
    }

    @Override
    public String component10() {
        return getSuperCaseInstanceId_();
    }

    @Override
    public String component11() {
        return getSuperProcessInstanceId_();
    }

    @Override
    public String component12() {
        return getTenantId_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getCaseInstId_();
    }

    @Override
    public String value3() {
        return getBusinessKey_();
    }

    @Override
    public String value4() {
        return getCaseDefId_();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime_();
    }

    @Override
    public LocalDateTime value6() {
        return getCloseTime_();
    }

    @Override
    public Long value7() {
        return getDuration_();
    }

    @Override
    public Integer value8() {
        return getState_();
    }

    @Override
    public String value9() {
        return getCreateUserId_();
    }

    @Override
    public String value10() {
        return getSuperCaseInstanceId_();
    }

    @Override
    public String value11() {
        return getSuperProcessInstanceId_();
    }

    @Override
    public String value12() {
        return getTenantId_();
    }

    @Override
    public ActHiCaseinstRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value2(String value) {
        setCaseInstId_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value3(String value) {
        setBusinessKey_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value4(String value) {
        setCaseDefId_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value5(LocalDateTime value) {
        setCreateTime_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value6(LocalDateTime value) {
        setCloseTime_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value7(Long value) {
        setDuration_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value8(Integer value) {
        setState_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value9(String value) {
        setCreateUserId_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value10(String value) {
        setSuperCaseInstanceId_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value11(String value) {
        setSuperProcessInstanceId_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord value12(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActHiCaseinstRecord values(String value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, Long value7, Integer value8, String value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiCaseinstRecord
     */
    public ActHiCaseinstRecord() {
        super(ActHiCaseinst.ACT_HI_CASEINST);
    }

    /**
     * Create a detached, initialised ActHiCaseinstRecord
     */
    public ActHiCaseinstRecord(String id_, String caseInstId_, String businessKey_, String caseDefId_, LocalDateTime createTime_, LocalDateTime closeTime_, Long duration_, Integer state_, String createUserId_, String superCaseInstanceId_, String superProcessInstanceId_, String tenantId_) {
        super(ActHiCaseinst.ACT_HI_CASEINST);

        setId_(id_);
        setCaseInstId_(caseInstId_);
        setBusinessKey_(businessKey_);
        setCaseDefId_(caseDefId_);
        setCreateTime_(createTime_);
        setCloseTime_(closeTime_);
        setDuration_(duration_);
        setState_(state_);
        setCreateUserId_(createUserId_);
        setSuperCaseInstanceId_(superCaseInstanceId_);
        setSuperProcessInstanceId_(superProcessInstanceId_);
        setTenantId_(tenantId_);
        resetChangedOnNotNull();
    }
}
