/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActHiCaseactinst;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiCaseactinstRecord extends UpdatableRecordImpl<ActHiCaseactinstRecord> implements Record16<String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Long, Integer, Boolean, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_hi_caseactinst.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.parent_act_inst_id_</code>.
     */
    public void setParentActInstId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.parent_act_inst_id_</code>.
     */
    public String getParentActInstId_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.case_def_id_</code>.
     */
    public void setCaseDefId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.case_def_id_</code>.
     */
    public String getCaseDefId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.case_inst_id_</code>.
     */
    public void setCaseInstId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.case_inst_id_</code>.
     */
    public String getCaseInstId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.case_act_id_</code>.
     */
    public void setCaseActId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.case_act_id_</code>.
     */
    public String getCaseActId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.task_id_</code>.
     */
    public void setTaskId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.task_id_</code>.
     */
    public String getTaskId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.call_proc_inst_id_</code>.
     */
    public void setCallProcInstId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.call_proc_inst_id_</code>.
     */
    public String getCallProcInstId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.call_case_inst_id_</code>.
     */
    public void setCallCaseInstId_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.call_case_inst_id_</code>.
     */
    public String getCallCaseInstId_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.case_act_name_</code>.
     */
    public void setCaseActName_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.case_act_name_</code>.
     */
    public String getCaseActName_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.case_act_type_</code>.
     */
    public void setCaseActType_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.case_act_type_</code>.
     */
    public String getCaseActType_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.create_time_</code>.
     */
    public void setCreateTime_(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.create_time_</code>.
     */
    public LocalDateTime getCreateTime_() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.end_time_</code>.
     */
    public void setEndTime_(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.end_time_</code>.
     */
    public LocalDateTime getEndTime_() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.duration_</code>.
     */
    public void setDuration_(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.duration_</code>.
     */
    public Long getDuration_() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.state_</code>.
     */
    public void setState_(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.state_</code>.
     */
    public Integer getState_() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.required_</code>.
     */
    public void setRequired_(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.required_</code>.
     */
    public Boolean getRequired_() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>greygold.act_hi_caseactinst.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>greygold.act_hi_caseactinst.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Long, Integer, Boolean, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Long, Integer, Boolean, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.ID_;
    }

    @Override
    public Field<String> field2() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.PARENT_ACT_INST_ID_;
    }

    @Override
    public Field<String> field3() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.CASE_DEF_ID_;
    }

    @Override
    public Field<String> field4() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.CASE_INST_ID_;
    }

    @Override
    public Field<String> field5() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.CASE_ACT_ID_;
    }

    @Override
    public Field<String> field6() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.TASK_ID_;
    }

    @Override
    public Field<String> field7() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.CALL_PROC_INST_ID_;
    }

    @Override
    public Field<String> field8() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.CALL_CASE_INST_ID_;
    }

    @Override
    public Field<String> field9() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.CASE_ACT_NAME_;
    }

    @Override
    public Field<String> field10() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.CASE_ACT_TYPE_;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.CREATE_TIME_;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.END_TIME_;
    }

    @Override
    public Field<Long> field13() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.DURATION_;
    }

    @Override
    public Field<Integer> field14() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.STATE_;
    }

    @Override
    public Field<Boolean> field15() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.REQUIRED_;
    }

    @Override
    public Field<String> field16() {
        return ActHiCaseactinst.ACT_HI_CASEACTINST.TENANT_ID_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getParentActInstId_();
    }

    @Override
    public String component3() {
        return getCaseDefId_();
    }

    @Override
    public String component4() {
        return getCaseInstId_();
    }

    @Override
    public String component5() {
        return getCaseActId_();
    }

    @Override
    public String component6() {
        return getTaskId_();
    }

    @Override
    public String component7() {
        return getCallProcInstId_();
    }

    @Override
    public String component8() {
        return getCallCaseInstId_();
    }

    @Override
    public String component9() {
        return getCaseActName_();
    }

    @Override
    public String component10() {
        return getCaseActType_();
    }

    @Override
    public LocalDateTime component11() {
        return getCreateTime_();
    }

    @Override
    public LocalDateTime component12() {
        return getEndTime_();
    }

    @Override
    public Long component13() {
        return getDuration_();
    }

    @Override
    public Integer component14() {
        return getState_();
    }

    @Override
    public Boolean component15() {
        return getRequired_();
    }

    @Override
    public String component16() {
        return getTenantId_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getParentActInstId_();
    }

    @Override
    public String value3() {
        return getCaseDefId_();
    }

    @Override
    public String value4() {
        return getCaseInstId_();
    }

    @Override
    public String value5() {
        return getCaseActId_();
    }

    @Override
    public String value6() {
        return getTaskId_();
    }

    @Override
    public String value7() {
        return getCallProcInstId_();
    }

    @Override
    public String value8() {
        return getCallCaseInstId_();
    }

    @Override
    public String value9() {
        return getCaseActName_();
    }

    @Override
    public String value10() {
        return getCaseActType_();
    }

    @Override
    public LocalDateTime value11() {
        return getCreateTime_();
    }

    @Override
    public LocalDateTime value12() {
        return getEndTime_();
    }

    @Override
    public Long value13() {
        return getDuration_();
    }

    @Override
    public Integer value14() {
        return getState_();
    }

    @Override
    public Boolean value15() {
        return getRequired_();
    }

    @Override
    public String value16() {
        return getTenantId_();
    }

    @Override
    public ActHiCaseactinstRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value2(String value) {
        setParentActInstId_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value3(String value) {
        setCaseDefId_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value4(String value) {
        setCaseInstId_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value5(String value) {
        setCaseActId_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value6(String value) {
        setTaskId_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value7(String value) {
        setCallProcInstId_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value8(String value) {
        setCallCaseInstId_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value9(String value) {
        setCaseActName_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value10(String value) {
        setCaseActType_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value11(LocalDateTime value) {
        setCreateTime_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value12(LocalDateTime value) {
        setEndTime_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value13(Long value) {
        setDuration_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value14(Integer value) {
        setState_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value15(Boolean value) {
        setRequired_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord value16(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActHiCaseactinstRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12, Long value13, Integer value14, Boolean value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiCaseactinstRecord
     */
    public ActHiCaseactinstRecord() {
        super(ActHiCaseactinst.ACT_HI_CASEACTINST);
    }

    /**
     * Create a detached, initialised ActHiCaseactinstRecord
     */
    public ActHiCaseactinstRecord(String id_, String parentActInstId_, String caseDefId_, String caseInstId_, String caseActId_, String taskId_, String callProcInstId_, String callCaseInstId_, String caseActName_, String caseActType_, LocalDateTime createTime_, LocalDateTime endTime_, Long duration_, Integer state_, Boolean required_, String tenantId_) {
        super(ActHiCaseactinst.ACT_HI_CASEACTINST);

        setId_(id_);
        setParentActInstId_(parentActInstId_);
        setCaseDefId_(caseDefId_);
        setCaseInstId_(caseInstId_);
        setCaseActId_(caseActId_);
        setTaskId_(taskId_);
        setCallProcInstId_(callProcInstId_);
        setCallCaseInstId_(callCaseInstId_);
        setCaseActName_(caseActName_);
        setCaseActType_(caseActType_);
        setCreateTime_(createTime_);
        setEndTime_(endTime_);
        setDuration_(duration_);
        setState_(state_);
        setRequired_(required_);
        setTenantId_(tenantId_);
        resetChangedOnNotNull();
    }
}
