/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActHiDecOut;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiDecOutRecord extends UpdatableRecordImpl<ActHiDecOutRecord> implements Record17<String, String, String, String, String, Integer, String, String, String, Double, Long, String, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_hi_dec_out.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.dec_inst_id_</code>.
     */
    public void setDecInstId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.dec_inst_id_</code>.
     */
    public String getDecInstId_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.clause_id_</code>.
     */
    public void setClauseId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.clause_id_</code>.
     */
    public String getClauseId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.clause_name_</code>.
     */
    public void setClauseName_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.clause_name_</code>.
     */
    public String getClauseName_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.rule_id_</code>.
     */
    public void setRuleId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.rule_id_</code>.
     */
    public String getRuleId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.rule_order_</code>.
     */
    public void setRuleOrder_(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.rule_order_</code>.
     */
    public Integer getRuleOrder_() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.var_name_</code>.
     */
    public void setVarName_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.var_name_</code>.
     */
    public String getVarName_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.var_type_</code>.
     */
    public void setVarType_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.var_type_</code>.
     */
    public String getVarType_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.bytearray_id_</code>.
     */
    public void setBytearrayId_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.bytearray_id_</code>.
     */
    public String getBytearrayId_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.double_</code>.
     */
    public void setDouble_(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.double_</code>.
     */
    public Double getDouble_() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.long_</code>.
     */
    public void setLong_(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.long_</code>.
     */
    public Long getLong_() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.text_</code>.
     */
    public void setText_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.text_</code>.
     */
    public String getText_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.text2_</code>.
     */
    public void setText2_(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.text2_</code>.
     */
    public String getText2_() {
        return (String) get(12);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.create_time_</code>.
     */
    public void setCreateTime_(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.create_time_</code>.
     */
    public LocalDateTime getCreateTime_() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.root_proc_inst_id_</code>.
     */
    public void setRootProcInstId_(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.root_proc_inst_id_</code>.
     */
    public String getRootProcInstId_() {
        return (String) get(15);
    }

    /**
     * Setter for <code>greygold.act_hi_dec_out.removal_time_</code>.
     */
    public void setRemovalTime_(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>greygold.act_hi_dec_out.removal_time_</code>.
     */
    public LocalDateTime getRemovalTime_() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<String, String, String, String, String, Integer, String, String, String, Double, Long, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<String, String, String, String, String, Integer, String, String, String, Double, Long, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiDecOut.ACT_HI_DEC_OUT.ID_;
    }

    @Override
    public Field<String> field2() {
        return ActHiDecOut.ACT_HI_DEC_OUT.DEC_INST_ID_;
    }

    @Override
    public Field<String> field3() {
        return ActHiDecOut.ACT_HI_DEC_OUT.CLAUSE_ID_;
    }

    @Override
    public Field<String> field4() {
        return ActHiDecOut.ACT_HI_DEC_OUT.CLAUSE_NAME_;
    }

    @Override
    public Field<String> field5() {
        return ActHiDecOut.ACT_HI_DEC_OUT.RULE_ID_;
    }

    @Override
    public Field<Integer> field6() {
        return ActHiDecOut.ACT_HI_DEC_OUT.RULE_ORDER_;
    }

    @Override
    public Field<String> field7() {
        return ActHiDecOut.ACT_HI_DEC_OUT.VAR_NAME_;
    }

    @Override
    public Field<String> field8() {
        return ActHiDecOut.ACT_HI_DEC_OUT.VAR_TYPE_;
    }

    @Override
    public Field<String> field9() {
        return ActHiDecOut.ACT_HI_DEC_OUT.BYTEARRAY_ID_;
    }

    @Override
    public Field<Double> field10() {
        return ActHiDecOut.ACT_HI_DEC_OUT.DOUBLE_;
    }

    @Override
    public Field<Long> field11() {
        return ActHiDecOut.ACT_HI_DEC_OUT.LONG_;
    }

    @Override
    public Field<String> field12() {
        return ActHiDecOut.ACT_HI_DEC_OUT.TEXT_;
    }

    @Override
    public Field<String> field13() {
        return ActHiDecOut.ACT_HI_DEC_OUT.TEXT2_;
    }

    @Override
    public Field<String> field14() {
        return ActHiDecOut.ACT_HI_DEC_OUT.TENANT_ID_;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return ActHiDecOut.ACT_HI_DEC_OUT.CREATE_TIME_;
    }

    @Override
    public Field<String> field16() {
        return ActHiDecOut.ACT_HI_DEC_OUT.ROOT_PROC_INST_ID_;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return ActHiDecOut.ACT_HI_DEC_OUT.REMOVAL_TIME_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getDecInstId_();
    }

    @Override
    public String component3() {
        return getClauseId_();
    }

    @Override
    public String component4() {
        return getClauseName_();
    }

    @Override
    public String component5() {
        return getRuleId_();
    }

    @Override
    public Integer component6() {
        return getRuleOrder_();
    }

    @Override
    public String component7() {
        return getVarName_();
    }

    @Override
    public String component8() {
        return getVarType_();
    }

    @Override
    public String component9() {
        return getBytearrayId_();
    }

    @Override
    public Double component10() {
        return getDouble_();
    }

    @Override
    public Long component11() {
        return getLong_();
    }

    @Override
    public String component12() {
        return getText_();
    }

    @Override
    public String component13() {
        return getText2_();
    }

    @Override
    public String component14() {
        return getTenantId_();
    }

    @Override
    public LocalDateTime component15() {
        return getCreateTime_();
    }

    @Override
    public String component16() {
        return getRootProcInstId_();
    }

    @Override
    public LocalDateTime component17() {
        return getRemovalTime_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getDecInstId_();
    }

    @Override
    public String value3() {
        return getClauseId_();
    }

    @Override
    public String value4() {
        return getClauseName_();
    }

    @Override
    public String value5() {
        return getRuleId_();
    }

    @Override
    public Integer value6() {
        return getRuleOrder_();
    }

    @Override
    public String value7() {
        return getVarName_();
    }

    @Override
    public String value8() {
        return getVarType_();
    }

    @Override
    public String value9() {
        return getBytearrayId_();
    }

    @Override
    public Double value10() {
        return getDouble_();
    }

    @Override
    public Long value11() {
        return getLong_();
    }

    @Override
    public String value12() {
        return getText_();
    }

    @Override
    public String value13() {
        return getText2_();
    }

    @Override
    public String value14() {
        return getTenantId_();
    }

    @Override
    public LocalDateTime value15() {
        return getCreateTime_();
    }

    @Override
    public String value16() {
        return getRootProcInstId_();
    }

    @Override
    public LocalDateTime value17() {
        return getRemovalTime_();
    }

    @Override
    public ActHiDecOutRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value2(String value) {
        setDecInstId_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value3(String value) {
        setClauseId_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value4(String value) {
        setClauseName_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value5(String value) {
        setRuleId_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value6(Integer value) {
        setRuleOrder_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value7(String value) {
        setVarName_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value8(String value) {
        setVarType_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value9(String value) {
        setBytearrayId_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value10(Double value) {
        setDouble_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value11(Long value) {
        setLong_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value12(String value) {
        setText_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value13(String value) {
        setText2_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value14(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value15(LocalDateTime value) {
        setCreateTime_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value16(String value) {
        setRootProcInstId_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord value17(LocalDateTime value) {
        setRemovalTime_(value);
        return this;
    }

    @Override
    public ActHiDecOutRecord values(String value1, String value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9, Double value10, Long value11, String value12, String value13, String value14, LocalDateTime value15, String value16, LocalDateTime value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiDecOutRecord
     */
    public ActHiDecOutRecord() {
        super(ActHiDecOut.ACT_HI_DEC_OUT);
    }

    /**
     * Create a detached, initialised ActHiDecOutRecord
     */
    public ActHiDecOutRecord(String id_, String decInstId_, String clauseId_, String clauseName_, String ruleId_, Integer ruleOrder_, String varName_, String varType_, String bytearrayId_, Double double_, Long long_, String text_, String text2_, String tenantId_, LocalDateTime createTime_, String rootProcInstId_, LocalDateTime removalTime_) {
        super(ActHiDecOut.ACT_HI_DEC_OUT);

        setId_(id_);
        setDecInstId_(decInstId_);
        setClauseId_(clauseId_);
        setClauseName_(clauseName_);
        setRuleId_(ruleId_);
        setRuleOrder_(ruleOrder_);
        setVarName_(varName_);
        setVarType_(varType_);
        setBytearrayId_(bytearrayId_);
        setDouble_(double_);
        setLong_(long_);
        setText_(text_);
        setText2_(text2_);
        setTenantId_(tenantId_);
        setCreateTime_(createTime_);
        setRootProcInstId_(rootProcInstId_);
        setRemovalTime_(removalTime_);
        resetChangedOnNotNull();
    }
}
