/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActHiProcinst;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiProcinstRecord extends UpdatableRecordImpl<ActHiProcinstRecord> implements Record19<String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Long, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_hi_procinst.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.proc_inst_id_</code>.
     */
    public void setProcInstId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.proc_inst_id_</code>.
     */
    public String getProcInstId_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.business_key_</code>.
     */
    public void setBusinessKey_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.business_key_</code>.
     */
    public String getBusinessKey_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.proc_def_key_</code>.
     */
    public void setProcDefKey_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.proc_def_key_</code>.
     */
    public String getProcDefKey_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.proc_def_id_</code>.
     */
    public void setProcDefId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.proc_def_id_</code>.
     */
    public String getProcDefId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.start_time_</code>.
     */
    public void setStartTime_(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.start_time_</code>.
     */
    public LocalDateTime getStartTime_() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.end_time_</code>.
     */
    public void setEndTime_(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.end_time_</code>.
     */
    public LocalDateTime getEndTime_() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.removal_time_</code>.
     */
    public void setRemovalTime_(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.removal_time_</code>.
     */
    public LocalDateTime getRemovalTime_() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.duration_</code>.
     */
    public void setDuration_(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.duration_</code>.
     */
    public Long getDuration_() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.start_user_id_</code>.
     */
    public void setStartUserId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.start_user_id_</code>.
     */
    public String getStartUserId_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.start_act_id_</code>.
     */
    public void setStartActId_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.start_act_id_</code>.
     */
    public String getStartActId_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.end_act_id_</code>.
     */
    public void setEndActId_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.end_act_id_</code>.
     */
    public String getEndActId_() {
        return (String) get(11);
    }

    /**
     * Setter for
     * <code>greygold.act_hi_procinst.super_process_instance_id_</code>.
     */
    public void setSuperProcessInstanceId_(String value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>greygold.act_hi_procinst.super_process_instance_id_</code>.
     */
    public String getSuperProcessInstanceId_() {
        return (String) get(12);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.root_proc_inst_id_</code>.
     */
    public void setRootProcInstId_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.root_proc_inst_id_</code>.
     */
    public String getRootProcInstId_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.super_case_instance_id_</code>.
     */
    public void setSuperCaseInstanceId_(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.super_case_instance_id_</code>.
     */
    public String getSuperCaseInstanceId_() {
        return (String) get(14);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.case_inst_id_</code>.
     */
    public void setCaseInstId_(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.case_inst_id_</code>.
     */
    public String getCaseInstId_() {
        return (String) get(15);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.delete_reason_</code>.
     */
    public void setDeleteReason_(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.delete_reason_</code>.
     */
    public String getDeleteReason_() {
        return (String) get(16);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(17);
    }

    /**
     * Setter for <code>greygold.act_hi_procinst.state_</code>.
     */
    public void setState_(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>greygold.act_hi_procinst.state_</code>.
     */
    public String getState_() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Long, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime, Long, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiProcinst.ACT_HI_PROCINST.ID_;
    }

    @Override
    public Field<String> field2() {
        return ActHiProcinst.ACT_HI_PROCINST.PROC_INST_ID_;
    }

    @Override
    public Field<String> field3() {
        return ActHiProcinst.ACT_HI_PROCINST.BUSINESS_KEY_;
    }

    @Override
    public Field<String> field4() {
        return ActHiProcinst.ACT_HI_PROCINST.PROC_DEF_KEY_;
    }

    @Override
    public Field<String> field5() {
        return ActHiProcinst.ACT_HI_PROCINST.PROC_DEF_ID_;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ActHiProcinst.ACT_HI_PROCINST.START_TIME_;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ActHiProcinst.ACT_HI_PROCINST.END_TIME_;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return ActHiProcinst.ACT_HI_PROCINST.REMOVAL_TIME_;
    }

    @Override
    public Field<Long> field9() {
        return ActHiProcinst.ACT_HI_PROCINST.DURATION_;
    }

    @Override
    public Field<String> field10() {
        return ActHiProcinst.ACT_HI_PROCINST.START_USER_ID_;
    }

    @Override
    public Field<String> field11() {
        return ActHiProcinst.ACT_HI_PROCINST.START_ACT_ID_;
    }

    @Override
    public Field<String> field12() {
        return ActHiProcinst.ACT_HI_PROCINST.END_ACT_ID_;
    }

    @Override
    public Field<String> field13() {
        return ActHiProcinst.ACT_HI_PROCINST.SUPER_PROCESS_INSTANCE_ID_;
    }

    @Override
    public Field<String> field14() {
        return ActHiProcinst.ACT_HI_PROCINST.ROOT_PROC_INST_ID_;
    }

    @Override
    public Field<String> field15() {
        return ActHiProcinst.ACT_HI_PROCINST.SUPER_CASE_INSTANCE_ID_;
    }

    @Override
    public Field<String> field16() {
        return ActHiProcinst.ACT_HI_PROCINST.CASE_INST_ID_;
    }

    @Override
    public Field<String> field17() {
        return ActHiProcinst.ACT_HI_PROCINST.DELETE_REASON_;
    }

    @Override
    public Field<String> field18() {
        return ActHiProcinst.ACT_HI_PROCINST.TENANT_ID_;
    }

    @Override
    public Field<String> field19() {
        return ActHiProcinst.ACT_HI_PROCINST.STATE_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getProcInstId_();
    }

    @Override
    public String component3() {
        return getBusinessKey_();
    }

    @Override
    public String component4() {
        return getProcDefKey_();
    }

    @Override
    public String component5() {
        return getProcDefId_();
    }

    @Override
    public LocalDateTime component6() {
        return getStartTime_();
    }

    @Override
    public LocalDateTime component7() {
        return getEndTime_();
    }

    @Override
    public LocalDateTime component8() {
        return getRemovalTime_();
    }

    @Override
    public Long component9() {
        return getDuration_();
    }

    @Override
    public String component10() {
        return getStartUserId_();
    }

    @Override
    public String component11() {
        return getStartActId_();
    }

    @Override
    public String component12() {
        return getEndActId_();
    }

    @Override
    public String component13() {
        return getSuperProcessInstanceId_();
    }

    @Override
    public String component14() {
        return getRootProcInstId_();
    }

    @Override
    public String component15() {
        return getSuperCaseInstanceId_();
    }

    @Override
    public String component16() {
        return getCaseInstId_();
    }

    @Override
    public String component17() {
        return getDeleteReason_();
    }

    @Override
    public String component18() {
        return getTenantId_();
    }

    @Override
    public String component19() {
        return getState_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getProcInstId_();
    }

    @Override
    public String value3() {
        return getBusinessKey_();
    }

    @Override
    public String value4() {
        return getProcDefKey_();
    }

    @Override
    public String value5() {
        return getProcDefId_();
    }

    @Override
    public LocalDateTime value6() {
        return getStartTime_();
    }

    @Override
    public LocalDateTime value7() {
        return getEndTime_();
    }

    @Override
    public LocalDateTime value8() {
        return getRemovalTime_();
    }

    @Override
    public Long value9() {
        return getDuration_();
    }

    @Override
    public String value10() {
        return getStartUserId_();
    }

    @Override
    public String value11() {
        return getStartActId_();
    }

    @Override
    public String value12() {
        return getEndActId_();
    }

    @Override
    public String value13() {
        return getSuperProcessInstanceId_();
    }

    @Override
    public String value14() {
        return getRootProcInstId_();
    }

    @Override
    public String value15() {
        return getSuperCaseInstanceId_();
    }

    @Override
    public String value16() {
        return getCaseInstId_();
    }

    @Override
    public String value17() {
        return getDeleteReason_();
    }

    @Override
    public String value18() {
        return getTenantId_();
    }

    @Override
    public String value19() {
        return getState_();
    }

    @Override
    public ActHiProcinstRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value2(String value) {
        setProcInstId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value3(String value) {
        setBusinessKey_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value4(String value) {
        setProcDefKey_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value5(String value) {
        setProcDefId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value6(LocalDateTime value) {
        setStartTime_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value7(LocalDateTime value) {
        setEndTime_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value8(LocalDateTime value) {
        setRemovalTime_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value9(Long value) {
        setDuration_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value10(String value) {
        setStartUserId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value11(String value) {
        setStartActId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value12(String value) {
        setEndActId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value13(String value) {
        setSuperProcessInstanceId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value14(String value) {
        setRootProcInstId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value15(String value) {
        setSuperCaseInstanceId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value16(String value) {
        setCaseInstId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value17(String value) {
        setDeleteReason_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value18(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord value19(String value) {
        setState_(value);
        return this;
    }

    @Override
    public ActHiProcinstRecord values(String value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7, LocalDateTime value8, Long value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiProcinstRecord
     */
    public ActHiProcinstRecord() {
        super(ActHiProcinst.ACT_HI_PROCINST);
    }

    /**
     * Create a detached, initialised ActHiProcinstRecord
     */
    public ActHiProcinstRecord(String id_, String procInstId_, String businessKey_, String procDefKey_, String procDefId_, LocalDateTime startTime_, LocalDateTime endTime_, LocalDateTime removalTime_, Long duration_, String startUserId_, String startActId_, String endActId_, String superProcessInstanceId_, String rootProcInstId_, String superCaseInstanceId_, String caseInstId_, String deleteReason_, String tenantId_, String state_) {
        super(ActHiProcinst.ACT_HI_PROCINST);

        setId_(id_);
        setProcInstId_(procInstId_);
        setBusinessKey_(businessKey_);
        setProcDefKey_(procDefKey_);
        setProcDefId_(procDefId_);
        setStartTime_(startTime_);
        setEndTime_(endTime_);
        setRemovalTime_(removalTime_);
        setDuration_(duration_);
        setStartUserId_(startUserId_);
        setStartActId_(startActId_);
        setEndActId_(endActId_);
        setSuperProcessInstanceId_(superProcessInstanceId_);
        setRootProcInstId_(rootProcInstId_);
        setSuperCaseInstanceId_(superCaseInstanceId_);
        setCaseInstId_(caseInstId_);
        setDeleteReason_(deleteReason_);
        setTenantId_(tenantId_);
        setState_(state_);
        resetChangedOnNotNull();
    }
}
