/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActHiDetail;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiDetailRecord extends UpdatableRecordImpl<ActHiDetailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_hi_detail.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.type_</code>.
     */
    public void setType_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.type_</code>.
     */
    public String getType_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.proc_def_key_</code>.
     */
    public void setProcDefKey_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.proc_def_key_</code>.
     */
    public String getProcDefKey_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.proc_def_id_</code>.
     */
    public void setProcDefId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.proc_def_id_</code>.
     */
    public String getProcDefId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.root_proc_inst_id_</code>.
     */
    public void setRootProcInstId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.root_proc_inst_id_</code>.
     */
    public String getRootProcInstId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.proc_inst_id_</code>.
     */
    public void setProcInstId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.proc_inst_id_</code>.
     */
    public String getProcInstId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.execution_id_</code>.
     */
    public void setExecutionId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.execution_id_</code>.
     */
    public String getExecutionId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.case_def_key_</code>.
     */
    public void setCaseDefKey_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.case_def_key_</code>.
     */
    public String getCaseDefKey_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.case_def_id_</code>.
     */
    public void setCaseDefId_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.case_def_id_</code>.
     */
    public String getCaseDefId_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.case_inst_id_</code>.
     */
    public void setCaseInstId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.case_inst_id_</code>.
     */
    public String getCaseInstId_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.case_execution_id_</code>.
     */
    public void setCaseExecutionId_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.case_execution_id_</code>.
     */
    public String getCaseExecutionId_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.task_id_</code>.
     */
    public void setTaskId_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.task_id_</code>.
     */
    public String getTaskId_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.act_inst_id_</code>.
     */
    public void setActInstId_(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.act_inst_id_</code>.
     */
    public String getActInstId_() {
        return (String) get(12);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.var_inst_id_</code>.
     */
    public void setVarInstId_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.var_inst_id_</code>.
     */
    public String getVarInstId_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.name_</code>.
     */
    public void setName_(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.name_</code>.
     */
    public String getName_() {
        return (String) get(14);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.var_type_</code>.
     */
    public void setVarType_(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.var_type_</code>.
     */
    public String getVarType_() {
        return (String) get(15);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.rev_</code>.
     */
    public void setRev_(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.rev_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.time_</code>.
     */
    public void setTime_(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.time_</code>.
     */
    public LocalDateTime getTime_() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.bytearray_id_</code>.
     */
    public void setBytearrayId_(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.bytearray_id_</code>.
     */
    public String getBytearrayId_() {
        return (String) get(18);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.double_</code>.
     */
    public void setDouble_(Double value) {
        set(19, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.double_</code>.
     */
    public Double getDouble_() {
        return (Double) get(19);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.long_</code>.
     */
    public void setLong_(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.long_</code>.
     */
    public Long getLong_() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.text_</code>.
     */
    public void setText_(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.text_</code>.
     */
    public String getText_() {
        return (String) get(21);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.text2_</code>.
     */
    public void setText2_(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.text2_</code>.
     */
    public String getText2_() {
        return (String) get(22);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.sequence_counter_</code>.
     */
    public void setSequenceCounter_(Long value) {
        set(23, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.sequence_counter_</code>.
     */
    public Long getSequenceCounter_() {
        return (Long) get(23);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(24);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.operation_id_</code>.
     */
    public void setOperationId_(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.operation_id_</code>.
     */
    public String getOperationId_() {
        return (String) get(25);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.removal_time_</code>.
     */
    public void setRemovalTime_(LocalDateTime value) {
        set(26, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.removal_time_</code>.
     */
    public LocalDateTime getRemovalTime_() {
        return (LocalDateTime) get(26);
    }

    /**
     * Setter for <code>greygold.act_hi_detail.initial_</code>.
     */
    public void setInitial_(Boolean value) {
        set(27, value);
    }

    /**
     * Getter for <code>greygold.act_hi_detail.initial_</code>.
     */
    public Boolean getInitial_() {
        return (Boolean) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiDetailRecord
     */
    public ActHiDetailRecord() {
        super(ActHiDetail.ACT_HI_DETAIL);
    }

    /**
     * Create a detached, initialised ActHiDetailRecord
     */
    public ActHiDetailRecord(String id_, String type_, String procDefKey_, String procDefId_, String rootProcInstId_, String procInstId_, String executionId_, String caseDefKey_, String caseDefId_, String caseInstId_, String caseExecutionId_, String taskId_, String actInstId_, String varInstId_, String name_, String varType_, Integer rev_, LocalDateTime time_, String bytearrayId_, Double double_, Long long_, String text_, String text2_, Long sequenceCounter_, String tenantId_, String operationId_, LocalDateTime removalTime_, Boolean initial_) {
        super(ActHiDetail.ACT_HI_DETAIL);

        setId_(id_);
        setType_(type_);
        setProcDefKey_(procDefKey_);
        setProcDefId_(procDefId_);
        setRootProcInstId_(rootProcInstId_);
        setProcInstId_(procInstId_);
        setExecutionId_(executionId_);
        setCaseDefKey_(caseDefKey_);
        setCaseDefId_(caseDefId_);
        setCaseInstId_(caseInstId_);
        setCaseExecutionId_(caseExecutionId_);
        setTaskId_(taskId_);
        setActInstId_(actInstId_);
        setVarInstId_(varInstId_);
        setName_(name_);
        setVarType_(varType_);
        setRev_(rev_);
        setTime_(time_);
        setBytearrayId_(bytearrayId_);
        setDouble_(double_);
        setLong_(long_);
        setText_(text_);
        setText2_(text2_);
        setSequenceCounter_(sequenceCounter_);
        setTenantId_(tenantId_);
        setOperationId_(operationId_);
        setRemovalTime_(removalTime_);
        setInitial_(initial_);
        resetChangedOnNotNull();
    }
}
