/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActHiExtTaskLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiExtTaskLogRecord extends UpdatableRecordImpl<ActHiExtTaskLogRecord> implements Record19<String, LocalDateTime, String, Integer, String, String, Long, String, String, String, String, String, String, String, String, String, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.timestamp_</code>.
     */
    public void setTimestamp_(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.timestamp_</code>.
     */
    public LocalDateTime getTimestamp_() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.ext_task_id_</code>.
     */
    public void setExtTaskId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.ext_task_id_</code>.
     */
    public String getExtTaskId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.retries_</code>.
     */
    public void setRetries_(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.retries_</code>.
     */
    public Integer getRetries_() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.topic_name_</code>.
     */
    public void setTopicName_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.topic_name_</code>.
     */
    public String getTopicName_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.worker_id_</code>.
     */
    public void setWorkerId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.worker_id_</code>.
     */
    public String getWorkerId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.priority_</code>.
     */
    public void setPriority_(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.priority_</code>.
     */
    public Long getPriority_() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.error_msg_</code>.
     */
    public void setErrorMsg_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.error_msg_</code>.
     */
    public String getErrorMsg_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.error_details_id_</code>.
     */
    public void setErrorDetailsId_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.error_details_id_</code>.
     */
    public String getErrorDetailsId_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.act_id_</code>.
     */
    public void setActId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.act_id_</code>.
     */
    public String getActId_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.act_inst_id_</code>.
     */
    public void setActInstId_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.act_inst_id_</code>.
     */
    public String getActInstId_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.execution_id_</code>.
     */
    public void setExecutionId_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.execution_id_</code>.
     */
    public String getExecutionId_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.proc_inst_id_</code>.
     */
    public void setProcInstId_(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.proc_inst_id_</code>.
     */
    public String getProcInstId_() {
        return (String) get(12);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.root_proc_inst_id_</code>.
     */
    public void setRootProcInstId_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.root_proc_inst_id_</code>.
     */
    public String getRootProcInstId_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.proc_def_id_</code>.
     */
    public void setProcDefId_(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.proc_def_id_</code>.
     */
    public String getProcDefId_() {
        return (String) get(14);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.proc_def_key_</code>.
     */
    public void setProcDefKey_(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.proc_def_key_</code>.
     */
    public String getProcDefKey_() {
        return (String) get(15);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(16);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.state_</code>.
     */
    public void setState_(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.state_</code>.
     */
    public Integer getState_() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>greygold.act_hi_ext_task_log.removal_time_</code>.
     */
    public void setRemovalTime_(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>greygold.act_hi_ext_task_log.removal_time_</code>.
     */
    public LocalDateTime getRemovalTime_() {
        return (LocalDateTime) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<String, LocalDateTime, String, Integer, String, String, Long, String, String, String, String, String, String, String, String, String, String, Integer, LocalDateTime> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<String, LocalDateTime, String, Integer, String, String, Long, String, String, String, String, String, String, String, String, String, String, Integer, LocalDateTime> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.ID_;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.TIMESTAMP_;
    }

    @Override
    public Field<String> field3() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.EXT_TASK_ID_;
    }

    @Override
    public Field<Integer> field4() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.RETRIES_;
    }

    @Override
    public Field<String> field5() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.TOPIC_NAME_;
    }

    @Override
    public Field<String> field6() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.WORKER_ID_;
    }

    @Override
    public Field<Long> field7() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.PRIORITY_;
    }

    @Override
    public Field<String> field8() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.ERROR_MSG_;
    }

    @Override
    public Field<String> field9() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.ERROR_DETAILS_ID_;
    }

    @Override
    public Field<String> field10() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.ACT_ID_;
    }

    @Override
    public Field<String> field11() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.ACT_INST_ID_;
    }

    @Override
    public Field<String> field12() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.EXECUTION_ID_;
    }

    @Override
    public Field<String> field13() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.PROC_INST_ID_;
    }

    @Override
    public Field<String> field14() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.ROOT_PROC_INST_ID_;
    }

    @Override
    public Field<String> field15() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.PROC_DEF_ID_;
    }

    @Override
    public Field<String> field16() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.PROC_DEF_KEY_;
    }

    @Override
    public Field<String> field17() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.TENANT_ID_;
    }

    @Override
    public Field<Integer> field18() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.STATE_;
    }

    @Override
    public Field<LocalDateTime> field19() {
        return ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG.REMOVAL_TIME_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public LocalDateTime component2() {
        return getTimestamp_();
    }

    @Override
    public String component3() {
        return getExtTaskId_();
    }

    @Override
    public Integer component4() {
        return getRetries_();
    }

    @Override
    public String component5() {
        return getTopicName_();
    }

    @Override
    public String component6() {
        return getWorkerId_();
    }

    @Override
    public Long component7() {
        return getPriority_();
    }

    @Override
    public String component8() {
        return getErrorMsg_();
    }

    @Override
    public String component9() {
        return getErrorDetailsId_();
    }

    @Override
    public String component10() {
        return getActId_();
    }

    @Override
    public String component11() {
        return getActInstId_();
    }

    @Override
    public String component12() {
        return getExecutionId_();
    }

    @Override
    public String component13() {
        return getProcInstId_();
    }

    @Override
    public String component14() {
        return getRootProcInstId_();
    }

    @Override
    public String component15() {
        return getProcDefId_();
    }

    @Override
    public String component16() {
        return getProcDefKey_();
    }

    @Override
    public String component17() {
        return getTenantId_();
    }

    @Override
    public Integer component18() {
        return getState_();
    }

    @Override
    public LocalDateTime component19() {
        return getRemovalTime_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public LocalDateTime value2() {
        return getTimestamp_();
    }

    @Override
    public String value3() {
        return getExtTaskId_();
    }

    @Override
    public Integer value4() {
        return getRetries_();
    }

    @Override
    public String value5() {
        return getTopicName_();
    }

    @Override
    public String value6() {
        return getWorkerId_();
    }

    @Override
    public Long value7() {
        return getPriority_();
    }

    @Override
    public String value8() {
        return getErrorMsg_();
    }

    @Override
    public String value9() {
        return getErrorDetailsId_();
    }

    @Override
    public String value10() {
        return getActId_();
    }

    @Override
    public String value11() {
        return getActInstId_();
    }

    @Override
    public String value12() {
        return getExecutionId_();
    }

    @Override
    public String value13() {
        return getProcInstId_();
    }

    @Override
    public String value14() {
        return getRootProcInstId_();
    }

    @Override
    public String value15() {
        return getProcDefId_();
    }

    @Override
    public String value16() {
        return getProcDefKey_();
    }

    @Override
    public String value17() {
        return getTenantId_();
    }

    @Override
    public Integer value18() {
        return getState_();
    }

    @Override
    public LocalDateTime value19() {
        return getRemovalTime_();
    }

    @Override
    public ActHiExtTaskLogRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value2(LocalDateTime value) {
        setTimestamp_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value3(String value) {
        setExtTaskId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value4(Integer value) {
        setRetries_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value5(String value) {
        setTopicName_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value6(String value) {
        setWorkerId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value7(Long value) {
        setPriority_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value8(String value) {
        setErrorMsg_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value9(String value) {
        setErrorDetailsId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value10(String value) {
        setActId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value11(String value) {
        setActInstId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value12(String value) {
        setExecutionId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value13(String value) {
        setProcInstId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value14(String value) {
        setRootProcInstId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value15(String value) {
        setProcDefId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value16(String value) {
        setProcDefKey_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value17(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value18(Integer value) {
        setState_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord value19(LocalDateTime value) {
        setRemovalTime_(value);
        return this;
    }

    @Override
    public ActHiExtTaskLogRecord values(String value1, LocalDateTime value2, String value3, Integer value4, String value5, String value6, Long value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, Integer value18, LocalDateTime value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiExtTaskLogRecord
     */
    public ActHiExtTaskLogRecord() {
        super(ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG);
    }

    /**
     * Create a detached, initialised ActHiExtTaskLogRecord
     */
    public ActHiExtTaskLogRecord(String id_, LocalDateTime timestamp_, String extTaskId_, Integer retries_, String topicName_, String workerId_, Long priority_, String errorMsg_, String errorDetailsId_, String actId_, String actInstId_, String executionId_, String procInstId_, String rootProcInstId_, String procDefId_, String procDefKey_, String tenantId_, Integer state_, LocalDateTime removalTime_) {
        super(ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG);

        setId_(id_);
        setTimestamp_(timestamp_);
        setExtTaskId_(extTaskId_);
        setRetries_(retries_);
        setTopicName_(topicName_);
        setWorkerId_(workerId_);
        setPriority_(priority_);
        setErrorMsg_(errorMsg_);
        setErrorDetailsId_(errorDetailsId_);
        setActId_(actId_);
        setActInstId_(actInstId_);
        setExecutionId_(executionId_);
        setProcInstId_(procInstId_);
        setRootProcInstId_(rootProcInstId_);
        setProcDefId_(procDefId_);
        setProcDefKey_(procDefKey_);
        setTenantId_(tenantId_);
        setState_(state_);
        setRemovalTime_(removalTime_);
        resetChangedOnNotNull();
    }
}
