/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActHiComment;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiCommentRecord extends UpdatableRecordImpl<ActHiCommentRecord> implements Record12<String, String, LocalDateTime, String, String, String, String, String, String, byte[], String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_hi_comment.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.type_</code>.
     */
    public void setType_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.type_</code>.
     */
    public String getType_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.time_</code>.
     */
    public void setTime_(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.time_</code>.
     */
    public LocalDateTime getTime_() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.user_id_</code>.
     */
    public void setUserId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.user_id_</code>.
     */
    public String getUserId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.task_id_</code>.
     */
    public void setTaskId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.task_id_</code>.
     */
    public String getTaskId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.root_proc_inst_id_</code>.
     */
    public void setRootProcInstId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.root_proc_inst_id_</code>.
     */
    public String getRootProcInstId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.proc_inst_id_</code>.
     */
    public void setProcInstId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.proc_inst_id_</code>.
     */
    public String getProcInstId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.action_</code>.
     */
    public void setAction_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.action_</code>.
     */
    public String getAction_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.message_</code>.
     */
    public void setMessage_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.message_</code>.
     */
    public String getMessage_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.full_msg_</code>.
     */
    public void setFullMsg_(byte[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.full_msg_</code>.
     */
    public byte[] getFullMsg_() {
        return (byte[]) get(9);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>greygold.act_hi_comment.removal_time_</code>.
     */
    public void setRemovalTime_(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_hi_comment.removal_time_</code>.
     */
    public LocalDateTime getRemovalTime_() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, String, LocalDateTime, String, String, String, String, String, String, byte[], String, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<String, String, LocalDateTime, String, String, String, String, String, String, byte[], String, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiComment.ACT_HI_COMMENT.ID_;
    }

    @Override
    public Field<String> field2() {
        return ActHiComment.ACT_HI_COMMENT.TYPE_;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ActHiComment.ACT_HI_COMMENT.TIME_;
    }

    @Override
    public Field<String> field4() {
        return ActHiComment.ACT_HI_COMMENT.USER_ID_;
    }

    @Override
    public Field<String> field5() {
        return ActHiComment.ACT_HI_COMMENT.TASK_ID_;
    }

    @Override
    public Field<String> field6() {
        return ActHiComment.ACT_HI_COMMENT.ROOT_PROC_INST_ID_;
    }

    @Override
    public Field<String> field7() {
        return ActHiComment.ACT_HI_COMMENT.PROC_INST_ID_;
    }

    @Override
    public Field<String> field8() {
        return ActHiComment.ACT_HI_COMMENT.ACTION_;
    }

    @Override
    public Field<String> field9() {
        return ActHiComment.ACT_HI_COMMENT.MESSAGE_;
    }

    @Override
    public Field<byte[]> field10() {
        return ActHiComment.ACT_HI_COMMENT.FULL_MSG_;
    }

    @Override
    public Field<String> field11() {
        return ActHiComment.ACT_HI_COMMENT.TENANT_ID_;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return ActHiComment.ACT_HI_COMMENT.REMOVAL_TIME_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public String component2() {
        return getType_();
    }

    @Override
    public LocalDateTime component3() {
        return getTime_();
    }

    @Override
    public String component4() {
        return getUserId_();
    }

    @Override
    public String component5() {
        return getTaskId_();
    }

    @Override
    public String component6() {
        return getRootProcInstId_();
    }

    @Override
    public String component7() {
        return getProcInstId_();
    }

    @Override
    public String component8() {
        return getAction_();
    }

    @Override
    public String component9() {
        return getMessage_();
    }

    @Override
    public byte[] component10() {
        return getFullMsg_();
    }

    @Override
    public String component11() {
        return getTenantId_();
    }

    @Override
    public LocalDateTime component12() {
        return getRemovalTime_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public String value2() {
        return getType_();
    }

    @Override
    public LocalDateTime value3() {
        return getTime_();
    }

    @Override
    public String value4() {
        return getUserId_();
    }

    @Override
    public String value5() {
        return getTaskId_();
    }

    @Override
    public String value6() {
        return getRootProcInstId_();
    }

    @Override
    public String value7() {
        return getProcInstId_();
    }

    @Override
    public String value8() {
        return getAction_();
    }

    @Override
    public String value9() {
        return getMessage_();
    }

    @Override
    public byte[] value10() {
        return getFullMsg_();
    }

    @Override
    public String value11() {
        return getTenantId_();
    }

    @Override
    public LocalDateTime value12() {
        return getRemovalTime_();
    }

    @Override
    public ActHiCommentRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value2(String value) {
        setType_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value3(LocalDateTime value) {
        setTime_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value4(String value) {
        setUserId_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value5(String value) {
        setTaskId_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value6(String value) {
        setRootProcInstId_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value7(String value) {
        setProcInstId_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value8(String value) {
        setAction_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value9(String value) {
        setMessage_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value10(byte[] value) {
        setFullMsg_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value11(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord value12(LocalDateTime value) {
        setRemovalTime_(value);
        return this;
    }

    @Override
    public ActHiCommentRecord values(String value1, String value2, LocalDateTime value3, String value4, String value5, String value6, String value7, String value8, String value9, byte[] value10, String value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiCommentRecord
     */
    public ActHiCommentRecord() {
        super(ActHiComment.ACT_HI_COMMENT);
    }

    /**
     * Create a detached, initialised ActHiCommentRecord
     */
    public ActHiCommentRecord(String id_, String type_, LocalDateTime time_, String userId_, String taskId_, String rootProcInstId_, String procInstId_, String action_, String message_, byte[] fullMsg_, String tenantId_, LocalDateTime removalTime_) {
        super(ActHiComment.ACT_HI_COMMENT);

        setId_(id_);
        setType_(type_);
        setTime_(time_);
        setUserId_(userId_);
        setTaskId_(taskId_);
        setRootProcInstId_(rootProcInstId_);
        setProcInstId_(procInstId_);
        setAction_(action_);
        setMessage_(message_);
        setFullMsg_(fullMsg_);
        setTenantId_(tenantId_);
        setRemovalTime_(removalTime_);
        resetChangedOnNotNull();
    }
}
