/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActHiIdentitylink;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiIdentitylinkRecord extends UpdatableRecordImpl<ActHiIdentitylinkRecord> implements Record13<String, LocalDateTime, String, String, String, String, String, String, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_hi_identitylink.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.timestamp_</code>.
     */
    public void setTimestamp_(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.timestamp_</code>.
     */
    public LocalDateTime getTimestamp_() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.type_</code>.
     */
    public void setType_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.type_</code>.
     */
    public String getType_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.user_id_</code>.
     */
    public void setUserId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.user_id_</code>.
     */
    public String getUserId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.group_id_</code>.
     */
    public void setGroupId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.group_id_</code>.
     */
    public String getGroupId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.task_id_</code>.
     */
    public void setTaskId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.task_id_</code>.
     */
    public String getTaskId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.root_proc_inst_id_</code>.
     */
    public void setRootProcInstId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.root_proc_inst_id_</code>.
     */
    public String getRootProcInstId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.proc_def_id_</code>.
     */
    public void setProcDefId_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.proc_def_id_</code>.
     */
    public String getProcDefId_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.operation_type_</code>.
     */
    public void setOperationType_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.operation_type_</code>.
     */
    public String getOperationType_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.assigner_id_</code>.
     */
    public void setAssignerId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.assigner_id_</code>.
     */
    public String getAssignerId_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.proc_def_key_</code>.
     */
    public void setProcDefKey_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.proc_def_key_</code>.
     */
    public String getProcDefKey_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>greygold.act_hi_identitylink.removal_time_</code>.
     */
    public void setRemovalTime_(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>greygold.act_hi_identitylink.removal_time_</code>.
     */
    public LocalDateTime getRemovalTime_() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<String, LocalDateTime, String, String, String, String, String, String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<String, LocalDateTime, String, String, String, String, String, String, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.ID_;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.TIMESTAMP_;
    }

    @Override
    public Field<String> field3() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.TYPE_;
    }

    @Override
    public Field<String> field4() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.USER_ID_;
    }

    @Override
    public Field<String> field5() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.GROUP_ID_;
    }

    @Override
    public Field<String> field6() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.TASK_ID_;
    }

    @Override
    public Field<String> field7() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.ROOT_PROC_INST_ID_;
    }

    @Override
    public Field<String> field8() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.PROC_DEF_ID_;
    }

    @Override
    public Field<String> field9() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.OPERATION_TYPE_;
    }

    @Override
    public Field<String> field10() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.ASSIGNER_ID_;
    }

    @Override
    public Field<String> field11() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.PROC_DEF_KEY_;
    }

    @Override
    public Field<String> field12() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.TENANT_ID_;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return ActHiIdentitylink.ACT_HI_IDENTITYLINK.REMOVAL_TIME_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public LocalDateTime component2() {
        return getTimestamp_();
    }

    @Override
    public String component3() {
        return getType_();
    }

    @Override
    public String component4() {
        return getUserId_();
    }

    @Override
    public String component5() {
        return getGroupId_();
    }

    @Override
    public String component6() {
        return getTaskId_();
    }

    @Override
    public String component7() {
        return getRootProcInstId_();
    }

    @Override
    public String component8() {
        return getProcDefId_();
    }

    @Override
    public String component9() {
        return getOperationType_();
    }

    @Override
    public String component10() {
        return getAssignerId_();
    }

    @Override
    public String component11() {
        return getProcDefKey_();
    }

    @Override
    public String component12() {
        return getTenantId_();
    }

    @Override
    public LocalDateTime component13() {
        return getRemovalTime_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public LocalDateTime value2() {
        return getTimestamp_();
    }

    @Override
    public String value3() {
        return getType_();
    }

    @Override
    public String value4() {
        return getUserId_();
    }

    @Override
    public String value5() {
        return getGroupId_();
    }

    @Override
    public String value6() {
        return getTaskId_();
    }

    @Override
    public String value7() {
        return getRootProcInstId_();
    }

    @Override
    public String value8() {
        return getProcDefId_();
    }

    @Override
    public String value9() {
        return getOperationType_();
    }

    @Override
    public String value10() {
        return getAssignerId_();
    }

    @Override
    public String value11() {
        return getProcDefKey_();
    }

    @Override
    public String value12() {
        return getTenantId_();
    }

    @Override
    public LocalDateTime value13() {
        return getRemovalTime_();
    }

    @Override
    public ActHiIdentitylinkRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value2(LocalDateTime value) {
        setTimestamp_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value3(String value) {
        setType_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value4(String value) {
        setUserId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value5(String value) {
        setGroupId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value6(String value) {
        setTaskId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value7(String value) {
        setRootProcInstId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value8(String value) {
        setProcDefId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value9(String value) {
        setOperationType_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value10(String value) {
        setAssignerId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value11(String value) {
        setProcDefKey_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value12(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord value13(LocalDateTime value) {
        setRemovalTime_(value);
        return this;
    }

    @Override
    public ActHiIdentitylinkRecord values(String value1, LocalDateTime value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiIdentitylinkRecord
     */
    public ActHiIdentitylinkRecord() {
        super(ActHiIdentitylink.ACT_HI_IDENTITYLINK);
    }

    /**
     * Create a detached, initialised ActHiIdentitylinkRecord
     */
    public ActHiIdentitylinkRecord(String id_, LocalDateTime timestamp_, String type_, String userId_, String groupId_, String taskId_, String rootProcInstId_, String procDefId_, String operationType_, String assignerId_, String procDefKey_, String tenantId_, LocalDateTime removalTime_) {
        super(ActHiIdentitylink.ACT_HI_IDENTITYLINK);

        setId_(id_);
        setTimestamp_(timestamp_);
        setType_(type_);
        setUserId_(userId_);
        setGroupId_(groupId_);
        setTaskId_(taskId_);
        setRootProcInstId_(rootProcInstId_);
        setProcDefId_(procDefId_);
        setOperationType_(operationType_);
        setAssignerId_(assignerId_);
        setProcDefKey_(procDefKey_);
        setTenantId_(tenantId_);
        setRemovalTime_(removalTime_);
        resetChangedOnNotNull();
    }
}
