/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActHiOpLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActHiOpLogRecord extends UpdatableRecordImpl<ActHiOpLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_hi_op_log.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.deployment_id_</code>.
     */
    public void setDeploymentId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.deployment_id_</code>.
     */
    public String getDeploymentId_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.proc_def_id_</code>.
     */
    public void setProcDefId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.proc_def_id_</code>.
     */
    public String getProcDefId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.proc_def_key_</code>.
     */
    public void setProcDefKey_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.proc_def_key_</code>.
     */
    public String getProcDefKey_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.root_proc_inst_id_</code>.
     */
    public void setRootProcInstId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.root_proc_inst_id_</code>.
     */
    public String getRootProcInstId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.proc_inst_id_</code>.
     */
    public void setProcInstId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.proc_inst_id_</code>.
     */
    public String getProcInstId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.execution_id_</code>.
     */
    public void setExecutionId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.execution_id_</code>.
     */
    public String getExecutionId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.case_def_id_</code>.
     */
    public void setCaseDefId_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.case_def_id_</code>.
     */
    public String getCaseDefId_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.case_inst_id_</code>.
     */
    public void setCaseInstId_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.case_inst_id_</code>.
     */
    public String getCaseInstId_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.case_execution_id_</code>.
     */
    public void setCaseExecutionId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.case_execution_id_</code>.
     */
    public String getCaseExecutionId_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.task_id_</code>.
     */
    public void setTaskId_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.task_id_</code>.
     */
    public String getTaskId_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.job_id_</code>.
     */
    public void setJobId_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.job_id_</code>.
     */
    public String getJobId_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.job_def_id_</code>.
     */
    public void setJobDefId_(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.job_def_id_</code>.
     */
    public String getJobDefId_() {
        return (String) get(12);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.batch_id_</code>.
     */
    public void setBatchId_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.batch_id_</code>.
     */
    public String getBatchId_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.user_id_</code>.
     */
    public void setUserId_(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.user_id_</code>.
     */
    public String getUserId_() {
        return (String) get(14);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.timestamp_</code>.
     */
    public void setTimestamp_(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.timestamp_</code>.
     */
    public LocalDateTime getTimestamp_() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.operation_type_</code>.
     */
    public void setOperationType_(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.operation_type_</code>.
     */
    public String getOperationType_() {
        return (String) get(16);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.operation_id_</code>.
     */
    public void setOperationId_(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.operation_id_</code>.
     */
    public String getOperationId_() {
        return (String) get(17);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.entity_type_</code>.
     */
    public void setEntityType_(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.entity_type_</code>.
     */
    public String getEntityType_() {
        return (String) get(18);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.property_</code>.
     */
    public void setProperty_(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.property_</code>.
     */
    public String getProperty_() {
        return (String) get(19);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.org_value_</code>.
     */
    public void setOrgValue_(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.org_value_</code>.
     */
    public String getOrgValue_() {
        return (String) get(20);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.new_value_</code>.
     */
    public void setNewValue_(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.new_value_</code>.
     */
    public String getNewValue_() {
        return (String) get(21);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(22);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.removal_time_</code>.
     */
    public void setRemovalTime_(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.removal_time_</code>.
     */
    public LocalDateTime getRemovalTime_() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.category_</code>.
     */
    public void setCategory_(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.category_</code>.
     */
    public String getCategory_() {
        return (String) get(24);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.external_task_id_</code>.
     */
    public void setExternalTaskId_(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.external_task_id_</code>.
     */
    public String getExternalTaskId_() {
        return (String) get(25);
    }

    /**
     * Setter for <code>greygold.act_hi_op_log.annotation_</code>.
     */
    public void setAnnotation_(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>greygold.act_hi_op_log.annotation_</code>.
     */
    public String getAnnotation_() {
        return (String) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActHiOpLogRecord
     */
    public ActHiOpLogRecord() {
        super(ActHiOpLog.ACT_HI_OP_LOG);
    }

    /**
     * Create a detached, initialised ActHiOpLogRecord
     */
    public ActHiOpLogRecord(String id_, String deploymentId_, String procDefId_, String procDefKey_, String rootProcInstId_, String procInstId_, String executionId_, String caseDefId_, String caseInstId_, String caseExecutionId_, String taskId_, String jobId_, String jobDefId_, String batchId_, String userId_, LocalDateTime timestamp_, String operationType_, String operationId_, String entityType_, String property_, String orgValue_, String newValue_, String tenantId_, LocalDateTime removalTime_, String category_, String externalTaskId_, String annotation_) {
        super(ActHiOpLog.ACT_HI_OP_LOG);

        setId_(id_);
        setDeploymentId_(deploymentId_);
        setProcDefId_(procDefId_);
        setProcDefKey_(procDefKey_);
        setRootProcInstId_(rootProcInstId_);
        setProcInstId_(procInstId_);
        setExecutionId_(executionId_);
        setCaseDefId_(caseDefId_);
        setCaseInstId_(caseInstId_);
        setCaseExecutionId_(caseExecutionId_);
        setTaskId_(taskId_);
        setJobId_(jobId_);
        setJobDefId_(jobDefId_);
        setBatchId_(batchId_);
        setUserId_(userId_);
        setTimestamp_(timestamp_);
        setOperationType_(operationType_);
        setOperationId_(operationId_);
        setEntityType_(entityType_);
        setProperty_(property_);
        setOrgValue_(orgValue_);
        setNewValue_(newValue_);
        setTenantId_(tenantId_);
        setRemovalTime_(removalTime_);
        setCategory_(category_);
        setExternalTaskId_(externalTaskId_);
        setAnnotation_(annotation_);
        resetChangedOnNotNull();
    }
}
