/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActIdMembership;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActIdMembershipRecord extends UpdatableRecordImpl<ActIdMembershipRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_id_membership.user_id_</code>.
     */
    public void setUserId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_id_membership.user_id_</code>.
     */
    public String getUserId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_id_membership.group_id_</code>.
     */
    public void setGroupId_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_id_membership.group_id_</code>.
     */
    public String getGroupId_() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActIdMembership.ACT_ID_MEMBERSHIP.USER_ID_;
    }

    @Override
    public Field<String> field2() {
        return ActIdMembership.ACT_ID_MEMBERSHIP.GROUP_ID_;
    }

    @Override
    public String component1() {
        return getUserId_();
    }

    @Override
    public String component2() {
        return getGroupId_();
    }

    @Override
    public String value1() {
        return getUserId_();
    }

    @Override
    public String value2() {
        return getGroupId_();
    }

    @Override
    public ActIdMembershipRecord value1(String value) {
        setUserId_(value);
        return this;
    }

    @Override
    public ActIdMembershipRecord value2(String value) {
        setGroupId_(value);
        return this;
    }

    @Override
    public ActIdMembershipRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActIdMembershipRecord
     */
    public ActIdMembershipRecord() {
        super(ActIdMembership.ACT_ID_MEMBERSHIP);
    }

    /**
     * Create a detached, initialised ActIdMembershipRecord
     */
    public ActIdMembershipRecord(String userId_, String groupId_) {
        super(ActIdMembership.ACT_ID_MEMBERSHIP);

        setUserId_(userId_);
        setGroupId_(groupId_);
        resetChangedOnNotNull();
    }
}
