/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActIdUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActIdUserRecord extends UpdatableRecordImpl<ActIdUserRecord> implements Record10<String, Integer, String, String, String, String, String, LocalDateTime, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_id_user.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_id_user.rev_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.rev_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>greygold.act_id_user.first_</code>.
     */
    public void setFirst_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.first_</code>.
     */
    public String getFirst_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_id_user.last_</code>.
     */
    public void setLast_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.last_</code>.
     */
    public String getLast_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_id_user.email_</code>.
     */
    public void setEmail_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.email_</code>.
     */
    public String getEmail_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_id_user.pwd_</code>.
     */
    public void setPwd_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.pwd_</code>.
     */
    public String getPwd_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>greygold.act_id_user.salt_</code>.
     */
    public void setSalt_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.salt_</code>.
     */
    public String getSalt_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_id_user.lock_exp_time_</code>.
     */
    public void setLockExpTime_(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.lock_exp_time_</code>.
     */
    public LocalDateTime getLockExpTime_() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>greygold.act_id_user.attempts_</code>.
     */
    public void setAttempts_(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.attempts_</code>.
     */
    public Integer getAttempts_() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>greygold.act_id_user.picture_id_</code>.
     */
    public void setPictureId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_id_user.picture_id_</code>.
     */
    public String getPictureId_() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, Integer, String, String, String, String, String, LocalDateTime, Integer, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, Integer, String, String, String, String, String, LocalDateTime, Integer, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActIdUser.ACT_ID_USER.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return ActIdUser.ACT_ID_USER.REV_;
    }

    @Override
    public Field<String> field3() {
        return ActIdUser.ACT_ID_USER.FIRST_;
    }

    @Override
    public Field<String> field4() {
        return ActIdUser.ACT_ID_USER.LAST_;
    }

    @Override
    public Field<String> field5() {
        return ActIdUser.ACT_ID_USER.EMAIL_;
    }

    @Override
    public Field<String> field6() {
        return ActIdUser.ACT_ID_USER.PWD_;
    }

    @Override
    public Field<String> field7() {
        return ActIdUser.ACT_ID_USER.SALT_;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return ActIdUser.ACT_ID_USER.LOCK_EXP_TIME_;
    }

    @Override
    public Field<Integer> field9() {
        return ActIdUser.ACT_ID_USER.ATTEMPTS_;
    }

    @Override
    public Field<String> field10() {
        return ActIdUser.ACT_ID_USER.PICTURE_ID_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getRev_();
    }

    @Override
    public String component3() {
        return getFirst_();
    }

    @Override
    public String component4() {
        return getLast_();
    }

    @Override
    public String component5() {
        return getEmail_();
    }

    @Override
    public String component6() {
        return getPwd_();
    }

    @Override
    public String component7() {
        return getSalt_();
    }

    @Override
    public LocalDateTime component8() {
        return getLockExpTime_();
    }

    @Override
    public Integer component9() {
        return getAttempts_();
    }

    @Override
    public String component10() {
        return getPictureId_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getRev_();
    }

    @Override
    public String value3() {
        return getFirst_();
    }

    @Override
    public String value4() {
        return getLast_();
    }

    @Override
    public String value5() {
        return getEmail_();
    }

    @Override
    public String value6() {
        return getPwd_();
    }

    @Override
    public String value7() {
        return getSalt_();
    }

    @Override
    public LocalDateTime value8() {
        return getLockExpTime_();
    }

    @Override
    public Integer value9() {
        return getAttempts_();
    }

    @Override
    public String value10() {
        return getPictureId_();
    }

    @Override
    public ActIdUserRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value3(String value) {
        setFirst_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value4(String value) {
        setLast_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value5(String value) {
        setEmail_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value6(String value) {
        setPwd_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value7(String value) {
        setSalt_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value8(LocalDateTime value) {
        setLockExpTime_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value9(Integer value) {
        setAttempts_(value);
        return this;
    }

    @Override
    public ActIdUserRecord value10(String value) {
        setPictureId_(value);
        return this;
    }

    @Override
    public ActIdUserRecord values(String value1, Integer value2, String value3, String value4, String value5, String value6, String value7, LocalDateTime value8, Integer value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActIdUserRecord
     */
    public ActIdUserRecord() {
        super(ActIdUser.ACT_ID_USER);
    }

    /**
     * Create a detached, initialised ActIdUserRecord
     */
    public ActIdUserRecord(String id_, Integer rev_, String first_, String last_, String email_, String pwd_, String salt_, LocalDateTime lockExpTime_, Integer attempts_, String pictureId_) {
        super(ActIdUser.ACT_ID_USER);

        setId_(id_);
        setRev_(rev_);
        setFirst_(first_);
        setLast_(last_);
        setEmail_(email_);
        setPwd_(pwd_);
        setSalt_(salt_);
        setLockExpTime_(lockExpTime_);
        setAttempts_(attempts_);
        setPictureId_(pictureId_);
        resetChangedOnNotNull();
    }
}
