/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActRuIdentitylink;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuIdentitylinkRecord extends UpdatableRecordImpl<ActRuIdentitylinkRecord> implements Record8<String, Integer, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_ru_identitylink.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_ru_identitylink.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_ru_identitylink.rev_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_ru_identitylink.rev_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>greygold.act_ru_identitylink.group_id_</code>.
     */
    public void setGroupId_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_ru_identitylink.group_id_</code>.
     */
    public String getGroupId_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_ru_identitylink.type_</code>.
     */
    public void setType_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_ru_identitylink.type_</code>.
     */
    public String getType_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_ru_identitylink.user_id_</code>.
     */
    public void setUserId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_ru_identitylink.user_id_</code>.
     */
    public String getUserId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_ru_identitylink.task_id_</code>.
     */
    public void setTaskId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_ru_identitylink.task_id_</code>.
     */
    public String getTaskId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>greygold.act_ru_identitylink.proc_def_id_</code>.
     */
    public void setProcDefId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_ru_identitylink.proc_def_id_</code>.
     */
    public String getProcDefId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_ru_identitylink.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_ru_identitylink.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, Integer, String, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, Integer, String, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActRuIdentitylink.ACT_RU_IDENTITYLINK.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return ActRuIdentitylink.ACT_RU_IDENTITYLINK.REV_;
    }

    @Override
    public Field<String> field3() {
        return ActRuIdentitylink.ACT_RU_IDENTITYLINK.GROUP_ID_;
    }

    @Override
    public Field<String> field4() {
        return ActRuIdentitylink.ACT_RU_IDENTITYLINK.TYPE_;
    }

    @Override
    public Field<String> field5() {
        return ActRuIdentitylink.ACT_RU_IDENTITYLINK.USER_ID_;
    }

    @Override
    public Field<String> field6() {
        return ActRuIdentitylink.ACT_RU_IDENTITYLINK.TASK_ID_;
    }

    @Override
    public Field<String> field7() {
        return ActRuIdentitylink.ACT_RU_IDENTITYLINK.PROC_DEF_ID_;
    }

    @Override
    public Field<String> field8() {
        return ActRuIdentitylink.ACT_RU_IDENTITYLINK.TENANT_ID_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getRev_();
    }

    @Override
    public String component3() {
        return getGroupId_();
    }

    @Override
    public String component4() {
        return getType_();
    }

    @Override
    public String component5() {
        return getUserId_();
    }

    @Override
    public String component6() {
        return getTaskId_();
    }

    @Override
    public String component7() {
        return getProcDefId_();
    }

    @Override
    public String component8() {
        return getTenantId_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getRev_();
    }

    @Override
    public String value3() {
        return getGroupId_();
    }

    @Override
    public String value4() {
        return getType_();
    }

    @Override
    public String value5() {
        return getUserId_();
    }

    @Override
    public String value6() {
        return getTaskId_();
    }

    @Override
    public String value7() {
        return getProcDefId_();
    }

    @Override
    public String value8() {
        return getTenantId_();
    }

    @Override
    public ActRuIdentitylinkRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActRuIdentitylinkRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActRuIdentitylinkRecord value3(String value) {
        setGroupId_(value);
        return this;
    }

    @Override
    public ActRuIdentitylinkRecord value4(String value) {
        setType_(value);
        return this;
    }

    @Override
    public ActRuIdentitylinkRecord value5(String value) {
        setUserId_(value);
        return this;
    }

    @Override
    public ActRuIdentitylinkRecord value6(String value) {
        setTaskId_(value);
        return this;
    }

    @Override
    public ActRuIdentitylinkRecord value7(String value) {
        setProcDefId_(value);
        return this;
    }

    @Override
    public ActRuIdentitylinkRecord value8(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActRuIdentitylinkRecord values(String value1, Integer value2, String value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActRuIdentitylinkRecord
     */
    public ActRuIdentitylinkRecord() {
        super(ActRuIdentitylink.ACT_RU_IDENTITYLINK);
    }

    /**
     * Create a detached, initialised ActRuIdentitylinkRecord
     */
    public ActRuIdentitylinkRecord(String id_, Integer rev_, String groupId_, String type_, String userId_, String taskId_, String procDefId_, String tenantId_) {
        super(ActRuIdentitylink.ACT_RU_IDENTITYLINK);

        setId_(id_);
        setRev_(rev_);
        setGroupId_(groupId_);
        setType_(type_);
        setUserId_(userId_);
        setTaskId_(taskId_);
        setProcDefId_(procDefId_);
        setTenantId_(tenantId_);
        resetChangedOnNotNull();
    }
}
