/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActRuIncident;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuIncidentRecord extends UpdatableRecordImpl<ActRuIncidentRecord> implements Record16<String, Integer, LocalDateTime, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_ru_incident.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.rev_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.rev_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.incident_timestamp_</code>.
     */
    public void setIncidentTimestamp_(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.incident_timestamp_</code>.
     */
    public LocalDateTime getIncidentTimestamp_() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.incident_msg_</code>.
     */
    public void setIncidentMsg_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.incident_msg_</code>.
     */
    public String getIncidentMsg_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.incident_type_</code>.
     */
    public void setIncidentType_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.incident_type_</code>.
     */
    public String getIncidentType_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.execution_id_</code>.
     */
    public void setExecutionId_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.execution_id_</code>.
     */
    public String getExecutionId_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.activity_id_</code>.
     */
    public void setActivityId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.activity_id_</code>.
     */
    public String getActivityId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.failed_activity_id_</code>.
     */
    public void setFailedActivityId_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.failed_activity_id_</code>.
     */
    public String getFailedActivityId_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.proc_inst_id_</code>.
     */
    public void setProcInstId_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.proc_inst_id_</code>.
     */
    public String getProcInstId_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.proc_def_id_</code>.
     */
    public void setProcDefId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.proc_def_id_</code>.
     */
    public String getProcDefId_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.cause_incident_id_</code>.
     */
    public void setCauseIncidentId_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.cause_incident_id_</code>.
     */
    public String getCauseIncidentId_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.root_cause_incident_id_</code>.
     */
    public void setRootCauseIncidentId_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.root_cause_incident_id_</code>.
     */
    public String getRootCauseIncidentId_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.configuration_</code>.
     */
    public void setConfiguration_(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.configuration_</code>.
     */
    public String getConfiguration_() {
        return (String) get(12);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.job_def_id_</code>.
     */
    public void setJobDefId_(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.job_def_id_</code>.
     */
    public String getJobDefId_() {
        return (String) get(14);
    }

    /**
     * Setter for <code>greygold.act_ru_incident.annotation_</code>.
     */
    public void setAnnotation_(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>greygold.act_ru_incident.annotation_</code>.
     */
    public String getAnnotation_() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, Integer, LocalDateTime, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<String, Integer, LocalDateTime, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActRuIncident.ACT_RU_INCIDENT.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return ActRuIncident.ACT_RU_INCIDENT.REV_;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ActRuIncident.ACT_RU_INCIDENT.INCIDENT_TIMESTAMP_;
    }

    @Override
    public Field<String> field4() {
        return ActRuIncident.ACT_RU_INCIDENT.INCIDENT_MSG_;
    }

    @Override
    public Field<String> field5() {
        return ActRuIncident.ACT_RU_INCIDENT.INCIDENT_TYPE_;
    }

    @Override
    public Field<String> field6() {
        return ActRuIncident.ACT_RU_INCIDENT.EXECUTION_ID_;
    }

    @Override
    public Field<String> field7() {
        return ActRuIncident.ACT_RU_INCIDENT.ACTIVITY_ID_;
    }

    @Override
    public Field<String> field8() {
        return ActRuIncident.ACT_RU_INCIDENT.FAILED_ACTIVITY_ID_;
    }

    @Override
    public Field<String> field9() {
        return ActRuIncident.ACT_RU_INCIDENT.PROC_INST_ID_;
    }

    @Override
    public Field<String> field10() {
        return ActRuIncident.ACT_RU_INCIDENT.PROC_DEF_ID_;
    }

    @Override
    public Field<String> field11() {
        return ActRuIncident.ACT_RU_INCIDENT.CAUSE_INCIDENT_ID_;
    }

    @Override
    public Field<String> field12() {
        return ActRuIncident.ACT_RU_INCIDENT.ROOT_CAUSE_INCIDENT_ID_;
    }

    @Override
    public Field<String> field13() {
        return ActRuIncident.ACT_RU_INCIDENT.CONFIGURATION_;
    }

    @Override
    public Field<String> field14() {
        return ActRuIncident.ACT_RU_INCIDENT.TENANT_ID_;
    }

    @Override
    public Field<String> field15() {
        return ActRuIncident.ACT_RU_INCIDENT.JOB_DEF_ID_;
    }

    @Override
    public Field<String> field16() {
        return ActRuIncident.ACT_RU_INCIDENT.ANNOTATION_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getRev_();
    }

    @Override
    public LocalDateTime component3() {
        return getIncidentTimestamp_();
    }

    @Override
    public String component4() {
        return getIncidentMsg_();
    }

    @Override
    public String component5() {
        return getIncidentType_();
    }

    @Override
    public String component6() {
        return getExecutionId_();
    }

    @Override
    public String component7() {
        return getActivityId_();
    }

    @Override
    public String component8() {
        return getFailedActivityId_();
    }

    @Override
    public String component9() {
        return getProcInstId_();
    }

    @Override
    public String component10() {
        return getProcDefId_();
    }

    @Override
    public String component11() {
        return getCauseIncidentId_();
    }

    @Override
    public String component12() {
        return getRootCauseIncidentId_();
    }

    @Override
    public String component13() {
        return getConfiguration_();
    }

    @Override
    public String component14() {
        return getTenantId_();
    }

    @Override
    public String component15() {
        return getJobDefId_();
    }

    @Override
    public String component16() {
        return getAnnotation_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getRev_();
    }

    @Override
    public LocalDateTime value3() {
        return getIncidentTimestamp_();
    }

    @Override
    public String value4() {
        return getIncidentMsg_();
    }

    @Override
    public String value5() {
        return getIncidentType_();
    }

    @Override
    public String value6() {
        return getExecutionId_();
    }

    @Override
    public String value7() {
        return getActivityId_();
    }

    @Override
    public String value8() {
        return getFailedActivityId_();
    }

    @Override
    public String value9() {
        return getProcInstId_();
    }

    @Override
    public String value10() {
        return getProcDefId_();
    }

    @Override
    public String value11() {
        return getCauseIncidentId_();
    }

    @Override
    public String value12() {
        return getRootCauseIncidentId_();
    }

    @Override
    public String value13() {
        return getConfiguration_();
    }

    @Override
    public String value14() {
        return getTenantId_();
    }

    @Override
    public String value15() {
        return getJobDefId_();
    }

    @Override
    public String value16() {
        return getAnnotation_();
    }

    @Override
    public ActRuIncidentRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value3(LocalDateTime value) {
        setIncidentTimestamp_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value4(String value) {
        setIncidentMsg_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value5(String value) {
        setIncidentType_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value6(String value) {
        setExecutionId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value7(String value) {
        setActivityId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value8(String value) {
        setFailedActivityId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value9(String value) {
        setProcInstId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value10(String value) {
        setProcDefId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value11(String value) {
        setCauseIncidentId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value12(String value) {
        setRootCauseIncidentId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value13(String value) {
        setConfiguration_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value14(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value15(String value) {
        setJobDefId_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord value16(String value) {
        setAnnotation_(value);
        return this;
    }

    @Override
    public ActRuIncidentRecord values(String value1, Integer value2, LocalDateTime value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActRuIncidentRecord
     */
    public ActRuIncidentRecord() {
        super(ActRuIncident.ACT_RU_INCIDENT);
    }

    /**
     * Create a detached, initialised ActRuIncidentRecord
     */
    public ActRuIncidentRecord(String id_, Integer rev_, LocalDateTime incidentTimestamp_, String incidentMsg_, String incidentType_, String executionId_, String activityId_, String failedActivityId_, String procInstId_, String procDefId_, String causeIncidentId_, String rootCauseIncidentId_, String configuration_, String tenantId_, String jobDefId_, String annotation_) {
        super(ActRuIncident.ACT_RU_INCIDENT);

        setId_(id_);
        setRev_(rev_);
        setIncidentTimestamp_(incidentTimestamp_);
        setIncidentMsg_(incidentMsg_);
        setIncidentType_(incidentType_);
        setExecutionId_(executionId_);
        setActivityId_(activityId_);
        setFailedActivityId_(failedActivityId_);
        setProcInstId_(procInstId_);
        setProcDefId_(procDefId_);
        setCauseIncidentId_(causeIncidentId_);
        setRootCauseIncidentId_(rootCauseIncidentId_);
        setConfiguration_(configuration_);
        setTenantId_(tenantId_);
        setJobDefId_(jobDefId_);
        setAnnotation_(annotation_);
        resetChangedOnNotNull();
    }
}
