/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActRuBatch;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuBatchRecord extends UpdatableRecordImpl<ActRuBatchRecord> implements Record16<String, Integer, String, Integer, Integer, Integer, Integer, String, String, String, Integer, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_ru_batch.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.rev_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.rev_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.type_</code>.
     */
    public void setType_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.type_</code>.
     */
    public String getType_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.total_jobs_</code>.
     */
    public void setTotalJobs_(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.total_jobs_</code>.
     */
    public Integer getTotalJobs_() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.jobs_created_</code>.
     */
    public void setJobsCreated_(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.jobs_created_</code>.
     */
    public Integer getJobsCreated_() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.jobs_per_seed_</code>.
     */
    public void setJobsPerSeed_(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.jobs_per_seed_</code>.
     */
    public Integer getJobsPerSeed_() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.invocations_per_job_</code>.
     */
    public void setInvocationsPerJob_(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.invocations_per_job_</code>.
     */
    public Integer getInvocationsPerJob_() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.seed_job_def_id_</code>.
     */
    public void setSeedJobDefId_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.seed_job_def_id_</code>.
     */
    public String getSeedJobDefId_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.batch_job_def_id_</code>.
     */
    public void setBatchJobDefId_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.batch_job_def_id_</code>.
     */
    public String getBatchJobDefId_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.monitor_job_def_id_</code>.
     */
    public void setMonitorJobDefId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.monitor_job_def_id_</code>.
     */
    public String getMonitorJobDefId_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.suspension_state_</code>.
     */
    public void setSuspensionState_(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.suspension_state_</code>.
     */
    public Integer getSuspensionState_() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.configuration_</code>.
     */
    public void setConfiguration_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.configuration_</code>.
     */
    public String getConfiguration_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(12);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.create_user_id_</code>.
     */
    public void setCreateUserId_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.create_user_id_</code>.
     */
    public String getCreateUserId_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.start_time_</code>.
     */
    public void setStartTime_(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.start_time_</code>.
     */
    public LocalDateTime getStartTime_() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>greygold.act_ru_batch.exec_start_time_</code>.
     */
    public void setExecStartTime_(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>greygold.act_ru_batch.exec_start_time_</code>.
     */
    public LocalDateTime getExecStartTime_() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, Integer, String, Integer, Integer, Integer, Integer, String, String, String, Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<String, Integer, String, Integer, Integer, Integer, Integer, String, String, String, Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActRuBatch.ACT_RU_BATCH.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return ActRuBatch.ACT_RU_BATCH.REV_;
    }

    @Override
    public Field<String> field3() {
        return ActRuBatch.ACT_RU_BATCH.TYPE_;
    }

    @Override
    public Field<Integer> field4() {
        return ActRuBatch.ACT_RU_BATCH.TOTAL_JOBS_;
    }

    @Override
    public Field<Integer> field5() {
        return ActRuBatch.ACT_RU_BATCH.JOBS_CREATED_;
    }

    @Override
    public Field<Integer> field6() {
        return ActRuBatch.ACT_RU_BATCH.JOBS_PER_SEED_;
    }

    @Override
    public Field<Integer> field7() {
        return ActRuBatch.ACT_RU_BATCH.INVOCATIONS_PER_JOB_;
    }

    @Override
    public Field<String> field8() {
        return ActRuBatch.ACT_RU_BATCH.SEED_JOB_DEF_ID_;
    }

    @Override
    public Field<String> field9() {
        return ActRuBatch.ACT_RU_BATCH.BATCH_JOB_DEF_ID_;
    }

    @Override
    public Field<String> field10() {
        return ActRuBatch.ACT_RU_BATCH.MONITOR_JOB_DEF_ID_;
    }

    @Override
    public Field<Integer> field11() {
        return ActRuBatch.ACT_RU_BATCH.SUSPENSION_STATE_;
    }

    @Override
    public Field<String> field12() {
        return ActRuBatch.ACT_RU_BATCH.CONFIGURATION_;
    }

    @Override
    public Field<String> field13() {
        return ActRuBatch.ACT_RU_BATCH.TENANT_ID_;
    }

    @Override
    public Field<String> field14() {
        return ActRuBatch.ACT_RU_BATCH.CREATE_USER_ID_;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return ActRuBatch.ACT_RU_BATCH.START_TIME_;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return ActRuBatch.ACT_RU_BATCH.EXEC_START_TIME_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getRev_();
    }

    @Override
    public String component3() {
        return getType_();
    }

    @Override
    public Integer component4() {
        return getTotalJobs_();
    }

    @Override
    public Integer component5() {
        return getJobsCreated_();
    }

    @Override
    public Integer component6() {
        return getJobsPerSeed_();
    }

    @Override
    public Integer component7() {
        return getInvocationsPerJob_();
    }

    @Override
    public String component8() {
        return getSeedJobDefId_();
    }

    @Override
    public String component9() {
        return getBatchJobDefId_();
    }

    @Override
    public String component10() {
        return getMonitorJobDefId_();
    }

    @Override
    public Integer component11() {
        return getSuspensionState_();
    }

    @Override
    public String component12() {
        return getConfiguration_();
    }

    @Override
    public String component13() {
        return getTenantId_();
    }

    @Override
    public String component14() {
        return getCreateUserId_();
    }

    @Override
    public LocalDateTime component15() {
        return getStartTime_();
    }

    @Override
    public LocalDateTime component16() {
        return getExecStartTime_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getRev_();
    }

    @Override
    public String value3() {
        return getType_();
    }

    @Override
    public Integer value4() {
        return getTotalJobs_();
    }

    @Override
    public Integer value5() {
        return getJobsCreated_();
    }

    @Override
    public Integer value6() {
        return getJobsPerSeed_();
    }

    @Override
    public Integer value7() {
        return getInvocationsPerJob_();
    }

    @Override
    public String value8() {
        return getSeedJobDefId_();
    }

    @Override
    public String value9() {
        return getBatchJobDefId_();
    }

    @Override
    public String value10() {
        return getMonitorJobDefId_();
    }

    @Override
    public Integer value11() {
        return getSuspensionState_();
    }

    @Override
    public String value12() {
        return getConfiguration_();
    }

    @Override
    public String value13() {
        return getTenantId_();
    }

    @Override
    public String value14() {
        return getCreateUserId_();
    }

    @Override
    public LocalDateTime value15() {
        return getStartTime_();
    }

    @Override
    public LocalDateTime value16() {
        return getExecStartTime_();
    }

    @Override
    public ActRuBatchRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value3(String value) {
        setType_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value4(Integer value) {
        setTotalJobs_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value5(Integer value) {
        setJobsCreated_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value6(Integer value) {
        setJobsPerSeed_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value7(Integer value) {
        setInvocationsPerJob_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value8(String value) {
        setSeedJobDefId_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value9(String value) {
        setBatchJobDefId_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value10(String value) {
        setMonitorJobDefId_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value11(Integer value) {
        setSuspensionState_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value12(String value) {
        setConfiguration_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value13(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value14(String value) {
        setCreateUserId_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value15(LocalDateTime value) {
        setStartTime_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord value16(LocalDateTime value) {
        setExecStartTime_(value);
        return this;
    }

    @Override
    public ActRuBatchRecord values(String value1, Integer value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, String value8, String value9, String value10, Integer value11, String value12, String value13, String value14, LocalDateTime value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActRuBatchRecord
     */
    public ActRuBatchRecord() {
        super(ActRuBatch.ACT_RU_BATCH);
    }

    /**
     * Create a detached, initialised ActRuBatchRecord
     */
    public ActRuBatchRecord(String id_, Integer rev_, String type_, Integer totalJobs_, Integer jobsCreated_, Integer jobsPerSeed_, Integer invocationsPerJob_, String seedJobDefId_, String batchJobDefId_, String monitorJobDefId_, Integer suspensionState_, String configuration_, String tenantId_, String createUserId_, LocalDateTime startTime_, LocalDateTime execStartTime_) {
        super(ActRuBatch.ACT_RU_BATCH);

        setId_(id_);
        setRev_(rev_);
        setType_(type_);
        setTotalJobs_(totalJobs_);
        setJobsCreated_(jobsCreated_);
        setJobsPerSeed_(jobsPerSeed_);
        setInvocationsPerJob_(invocationsPerJob_);
        setSeedJobDefId_(seedJobDefId_);
        setBatchJobDefId_(batchJobDefId_);
        setMonitorJobDefId_(monitorJobDefId_);
        setSuspensionState_(suspensionState_);
        setConfiguration_(configuration_);
        setTenantId_(tenantId_);
        setCreateUserId_(createUserId_);
        setStartTime_(startTime_);
        setExecStartTime_(execStartTime_);
        resetChangedOnNotNull();
    }
}
