/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActRuAuthorization;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActRuAuthorizationRecord extends UpdatableRecordImpl<ActRuAuthorizationRecord> implements Record10<String, Integer, Integer, String, String, Integer, String, Integer, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_ru_authorization.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_ru_authorization.rev_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.rev_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>greygold.act_ru_authorization.type_</code>.
     */
    public void setType_(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.type_</code>.
     */
    public Integer getType_() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>greygold.act_ru_authorization.group_id_</code>.
     */
    public void setGroupId_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.group_id_</code>.
     */
    public String getGroupId_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_ru_authorization.user_id_</code>.
     */
    public void setUserId_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.user_id_</code>.
     */
    public String getUserId_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_ru_authorization.resource_type_</code>.
     */
    public void setResourceType_(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.resource_type_</code>.
     */
    public Integer getResourceType_() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>greygold.act_ru_authorization.resource_id_</code>.
     */
    public void setResourceId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.resource_id_</code>.
     */
    public String getResourceId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_ru_authorization.perms_</code>.
     */
    public void setPerms_(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.perms_</code>.
     */
    public Integer getPerms_() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>greygold.act_ru_authorization.removal_time_</code>.
     */
    public void setRemovalTime_(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.removal_time_</code>.
     */
    public LocalDateTime getRemovalTime_() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>greygold.act_ru_authorization.root_proc_inst_id_</code>.
     */
    public void setRootProcInstId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_ru_authorization.root_proc_inst_id_</code>.
     */
    public String getRootProcInstId_() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, Integer, Integer, String, String, Integer, String, Integer, LocalDateTime, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, Integer, Integer, String, String, Integer, String, Integer, LocalDateTime, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.REV_;
    }

    @Override
    public Field<Integer> field3() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.TYPE_;
    }

    @Override
    public Field<String> field4() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.GROUP_ID_;
    }

    @Override
    public Field<String> field5() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.USER_ID_;
    }

    @Override
    public Field<Integer> field6() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.RESOURCE_TYPE_;
    }

    @Override
    public Field<String> field7() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.RESOURCE_ID_;
    }

    @Override
    public Field<Integer> field8() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.PERMS_;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.REMOVAL_TIME_;
    }

    @Override
    public Field<String> field10() {
        return ActRuAuthorization.ACT_RU_AUTHORIZATION.ROOT_PROC_INST_ID_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getRev_();
    }

    @Override
    public Integer component3() {
        return getType_();
    }

    @Override
    public String component4() {
        return getGroupId_();
    }

    @Override
    public String component5() {
        return getUserId_();
    }

    @Override
    public Integer component6() {
        return getResourceType_();
    }

    @Override
    public String component7() {
        return getResourceId_();
    }

    @Override
    public Integer component8() {
        return getPerms_();
    }

    @Override
    public LocalDateTime component9() {
        return getRemovalTime_();
    }

    @Override
    public String component10() {
        return getRootProcInstId_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getRev_();
    }

    @Override
    public Integer value3() {
        return getType_();
    }

    @Override
    public String value4() {
        return getGroupId_();
    }

    @Override
    public String value5() {
        return getUserId_();
    }

    @Override
    public Integer value6() {
        return getResourceType_();
    }

    @Override
    public String value7() {
        return getResourceId_();
    }

    @Override
    public Integer value8() {
        return getPerms_();
    }

    @Override
    public LocalDateTime value9() {
        return getRemovalTime_();
    }

    @Override
    public String value10() {
        return getRootProcInstId_();
    }

    @Override
    public ActRuAuthorizationRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord value3(Integer value) {
        setType_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord value4(String value) {
        setGroupId_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord value5(String value) {
        setUserId_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord value6(Integer value) {
        setResourceType_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord value7(String value) {
        setResourceId_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord value8(Integer value) {
        setPerms_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord value9(LocalDateTime value) {
        setRemovalTime_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord value10(String value) {
        setRootProcInstId_(value);
        return this;
    }

    @Override
    public ActRuAuthorizationRecord values(String value1, Integer value2, Integer value3, String value4, String value5, Integer value6, String value7, Integer value8, LocalDateTime value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActRuAuthorizationRecord
     */
    public ActRuAuthorizationRecord() {
        super(ActRuAuthorization.ACT_RU_AUTHORIZATION);
    }

    /**
     * Create a detached, initialised ActRuAuthorizationRecord
     */
    public ActRuAuthorizationRecord(String id_, Integer rev_, Integer type_, String groupId_, String userId_, Integer resourceType_, String resourceId_, Integer perms_, LocalDateTime removalTime_, String rootProcInstId_) {
        super(ActRuAuthorization.ACT_RU_AUTHORIZATION);

        setId_(id_);
        setRev_(rev_);
        setType_(type_);
        setGroupId_(groupId_);
        setUserId_(userId_);
        setResourceType_(resourceType_);
        setResourceId_(resourceId_);
        setPerms_(perms_);
        setRemovalTime_(removalTime_);
        setRootProcInstId_(rootProcInstId_);
        resetChangedOnNotNull();
    }
}
