/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tito.jooq.tables.ActReDecisionReqDef;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActReDecisionReqDefRecord extends UpdatableRecordImpl<ActReDecisionReqDefRecord> implements Record10<String, Integer, String, String, String, Integer, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.act_re_decision_req_def.id_</code>.
     */
    public void setId_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.act_re_decision_req_def.id_</code>.
     */
    public String getId_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>greygold.act_re_decision_req_def.rev_</code>.
     */
    public void setRev_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.act_re_decision_req_def.rev_</code>.
     */
    public Integer getRev_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>greygold.act_re_decision_req_def.category_</code>.
     */
    public void setCategory_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.act_re_decision_req_def.category_</code>.
     */
    public String getCategory_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>greygold.act_re_decision_req_def.name_</code>.
     */
    public void setName_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.act_re_decision_req_def.name_</code>.
     */
    public String getName_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>greygold.act_re_decision_req_def.key_</code>.
     */
    public void setKey_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.act_re_decision_req_def.key_</code>.
     */
    public String getKey_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>greygold.act_re_decision_req_def.version_</code>.
     */
    public void setVersion_(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>greygold.act_re_decision_req_def.version_</code>.
     */
    public Integer getVersion_() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>greygold.act_re_decision_req_def.deployment_id_</code>.
     */
    public void setDeploymentId_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>greygold.act_re_decision_req_def.deployment_id_</code>.
     */
    public String getDeploymentId_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>greygold.act_re_decision_req_def.resource_name_</code>.
     */
    public void setResourceName_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>greygold.act_re_decision_req_def.resource_name_</code>.
     */
    public String getResourceName_() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>greygold.act_re_decision_req_def.dgrm_resource_name_</code>.
     */
    public void setDgrmResourceName_(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>greygold.act_re_decision_req_def.dgrm_resource_name_</code>.
     */
    public String getDgrmResourceName_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>greygold.act_re_decision_req_def.tenant_id_</code>.
     */
    public void setTenantId_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>greygold.act_re_decision_req_def.tenant_id_</code>.
     */
    public String getTenantId_() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, Integer, String, String, String, Integer, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, Integer, String, String, String, Integer, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.ID_;
    }

    @Override
    public Field<Integer> field2() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.REV_;
    }

    @Override
    public Field<String> field3() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.CATEGORY_;
    }

    @Override
    public Field<String> field4() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.NAME_;
    }

    @Override
    public Field<String> field5() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.KEY_;
    }

    @Override
    public Field<Integer> field6() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.VERSION_;
    }

    @Override
    public Field<String> field7() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.DEPLOYMENT_ID_;
    }

    @Override
    public Field<String> field8() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.RESOURCE_NAME_;
    }

    @Override
    public Field<String> field9() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.DGRM_RESOURCE_NAME_;
    }

    @Override
    public Field<String> field10() {
        return ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF.TENANT_ID_;
    }

    @Override
    public String component1() {
        return getId_();
    }

    @Override
    public Integer component2() {
        return getRev_();
    }

    @Override
    public String component3() {
        return getCategory_();
    }

    @Override
    public String component4() {
        return getName_();
    }

    @Override
    public String component5() {
        return getKey_();
    }

    @Override
    public Integer component6() {
        return getVersion_();
    }

    @Override
    public String component7() {
        return getDeploymentId_();
    }

    @Override
    public String component8() {
        return getResourceName_();
    }

    @Override
    public String component9() {
        return getDgrmResourceName_();
    }

    @Override
    public String component10() {
        return getTenantId_();
    }

    @Override
    public String value1() {
        return getId_();
    }

    @Override
    public Integer value2() {
        return getRev_();
    }

    @Override
    public String value3() {
        return getCategory_();
    }

    @Override
    public String value4() {
        return getName_();
    }

    @Override
    public String value5() {
        return getKey_();
    }

    @Override
    public Integer value6() {
        return getVersion_();
    }

    @Override
    public String value7() {
        return getDeploymentId_();
    }

    @Override
    public String value8() {
        return getResourceName_();
    }

    @Override
    public String value9() {
        return getDgrmResourceName_();
    }

    @Override
    public String value10() {
        return getTenantId_();
    }

    @Override
    public ActReDecisionReqDefRecord value1(String value) {
        setId_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord value2(Integer value) {
        setRev_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord value3(String value) {
        setCategory_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord value4(String value) {
        setName_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord value5(String value) {
        setKey_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord value6(Integer value) {
        setVersion_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord value7(String value) {
        setDeploymentId_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord value8(String value) {
        setResourceName_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord value9(String value) {
        setDgrmResourceName_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord value10(String value) {
        setTenantId_(value);
        return this;
    }

    @Override
    public ActReDecisionReqDefRecord values(String value1, Integer value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActReDecisionReqDefRecord
     */
    public ActReDecisionReqDefRecord() {
        super(ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF);
    }

    /**
     * Create a detached, initialised ActReDecisionReqDefRecord
     */
    public ActReDecisionReqDefRecord(String id_, Integer rev_, String category_, String name_, String key_, Integer version_, String deploymentId_, String resourceName_, String dgrmResourceName_, String tenantId_) {
        super(ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF);

        setId_(id_);
        setRev_(rev_);
        setCategory_(category_);
        setName_(name_);
        setKey_(key_);
        setVersion_(version_);
        setDeploymentId_(deploymentId_);
        setResourceName_(resourceName_);
        setDgrmResourceName_(dgrmResourceName_);
        setTenantId_(tenantId_);
        resetChangedOnNotNull();
    }
}
