/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.math.BigDecimal;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import ru.tito.jooq.tables.Demo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemoRecord extends TableRecordImpl<DemoRecord> implements Record5<Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.demo.id_</code>.
     */
    public void setId_(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.demo.id_</code>.
     */
    public Integer getId_() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>greygold.demo.cost_</code>.
     */
    public void setCost_(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.demo.cost_</code>.
     */
    public BigDecimal getCost_() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>greygold.demo.in_</code>.
     */
    public void setIn_(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>greygold.demo.in_</code>.
     */
    public BigDecimal getIn_() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>greygold.demo.cost_persent</code>.
     */
    public void setCostPersent(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>greygold.demo.cost_persent</code>.
     */
    public BigDecimal getCostPersent() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>greygold.demo.in_percent</code>.
     */
    public void setInPercent(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>greygold.demo.in_percent</code>.
     */
    public BigDecimal getInPercent() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Demo.DEMO.ID_;
    }

    @Override
    public Field<BigDecimal> field2() {
        return Demo.DEMO.COST_;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Demo.DEMO.IN_;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Demo.DEMO.COST_PERSENT;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Demo.DEMO.IN_PERCENT;
    }

    @Override
    public Integer component1() {
        return getId_();
    }

    @Override
    public BigDecimal component2() {
        return getCost_();
    }

    @Override
    public BigDecimal component3() {
        return getIn_();
    }

    @Override
    public BigDecimal component4() {
        return getCostPersent();
    }

    @Override
    public BigDecimal component5() {
        return getInPercent();
    }

    @Override
    public Integer value1() {
        return getId_();
    }

    @Override
    public BigDecimal value2() {
        return getCost_();
    }

    @Override
    public BigDecimal value3() {
        return getIn_();
    }

    @Override
    public BigDecimal value4() {
        return getCostPersent();
    }

    @Override
    public BigDecimal value5() {
        return getInPercent();
    }

    @Override
    public DemoRecord value1(Integer value) {
        setId_(value);
        return this;
    }

    @Override
    public DemoRecord value2(BigDecimal value) {
        setCost_(value);
        return this;
    }

    @Override
    public DemoRecord value3(BigDecimal value) {
        setIn_(value);
        return this;
    }

    @Override
    public DemoRecord value4(BigDecimal value) {
        setCostPersent(value);
        return this;
    }

    @Override
    public DemoRecord value5(BigDecimal value) {
        setInPercent(value);
        return this;
    }

    @Override
    public DemoRecord values(Integer value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, BigDecimal value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DemoRecord
     */
    public DemoRecord() {
        super(Demo.DEMO);
    }

    /**
     * Create a detached, initialised DemoRecord
     */
    public DemoRecord(Integer id_, BigDecimal cost_, BigDecimal in_, BigDecimal costPersent, BigDecimal inPercent) {
        super(Demo.DEMO);

        setId_(id_);
        setCost_(cost_);
        setIn_(in_);
        setCostPersent(costPersent);
        setInPercent(inPercent);
        resetChangedOnNotNull();
    }
}
