/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.tito.jooq.tables.Distgenseq;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistgenseqRecord extends TableRecordImpl<DistgenseqRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.distgenseq.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.distgenseq.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>greygold.distgenseq.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.distgenseq.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Distgenseq.DISTGENSEQ.ID;
    }

    @Override
    public Field<String> field2() {
        return Distgenseq.DISTGENSEQ.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public DistgenseqRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DistgenseqRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DistgenseqRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DistgenseqRecord
     */
    public DistgenseqRecord() {
        super(Distgenseq.DISTGENSEQ);
    }

    /**
     * Create a detached, initialised DistgenseqRecord
     */
    public DistgenseqRecord(Integer id, String name) {
        super(Distgenseq.DISTGENSEQ);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
