/*
 * This file is generated by jOOQ.
 */
package ru.tito.jooq.tables.records;


import java.math.BigDecimal;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.tito.jooq.tables.Graygold2;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Graygold2Record extends TableRecordImpl<Graygold2Record> implements Record2<BigDecimal, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>greygold.graygold2.id</code>.
     */
    public void setId(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>greygold.graygold2.id</code>.
     */
    public BigDecimal getId() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>greygold.graygold2.version</code>.
     */
    public void setVersion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>greygold.graygold2.version</code>.
     */
    public String getVersion() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<BigDecimal, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<BigDecimal, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<BigDecimal> field1() {
        return Graygold2.GRAYGOLD2.ID;
    }

    @Override
    public Field<String> field2() {
        return Graygold2.GRAYGOLD2.VERSION;
    }

    @Override
    public BigDecimal component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getVersion();
    }

    @Override
    public BigDecimal value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getVersion();
    }

    @Override
    public Graygold2Record value1(BigDecimal value) {
        setId(value);
        return this;
    }

    @Override
    public Graygold2Record value2(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public Graygold2Record values(BigDecimal value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Graygold2Record
     */
    public Graygold2Record() {
        super(Graygold2.GRAYGOLD2);
    }

    /**
     * Create a detached, initialised Graygold2Record
     */
    public Graygold2Record(BigDecimal id, String version) {
        super(Graygold2.GRAYGOLD2);

        setId(id);
        setVersion(version);
        resetChangedOnNotNull();
    }
}
